-- AGENCIA DE VIAJES

CREATE DATABASE AGENCIA_VIAJES;
USE AGENCIA_VIAJES;

CREATE TABLE EMPLEADOS (
ID INT PRIMARY KEY,
NOMBRE VARCHAR(100),
PUESTO VARCHAR(50)
);

CREATE TABLE RESERVAS (
ID INT PRIMARY KEY,
ID_CLIENTE INT,
ID_EMPLEADO INT,
ID_ALOJAMIENTO INT,
FECHA_ENTRADA DATE,
FECHA_SALIDA DATE
);

CREATE TABLE CLIENTES (
ID INT PRIMARY KEY,
NOMBRE VARCHAR(100),
TELEFONO VARCHAR(15)
);

CREATE TABLE ALOJAMIENTOS (
ID INT PRIMARY KEY,
NOMBRE VARCHAR(100),
LOCALIDAD VARCHAR(50),
PRECIO_NOCHE DECIMAL(6,2)
);

ALTER TABLE RESERVAS
ADD CONSTRAINT RESERVAS_ALOJAMIENTOS_FK
	FOREIGN KEY (ID_ALOJAMIENTO)
    REFERENCES ALOJAMIENTOS(ID)
    ON UPDATE CASCADE ON DELETE CASCADE,
ADD CONSTRAINT RESERVAS_CLIENTES_FK
	FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTES(ID)
    ON UPDATE CASCADE ON DELETE CASCADE,
ADD CONSTRAINT RESERVAS_EMPLEADOS_FK
	FOREIGN KEY (ID_EMPLEADO)
    REFERENCES EMPLEADOS(ID)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE CLIENTES 
ADD COLUMN EMAIL VARCHAR(100) AFTER NOMBRE;

INSERT INTO CLIENTES VALUES
(1, 'Ana Torres', 'ana.torres@gmail.com', '600123456'), 
(2, 'Luis García', 'luisg@hotmail.com', '655987654'), 
(3, 'Clara Ruiz', 'clara.ruiz@gmail.com', '677456789'); 

INSERT INTO EMPLEADOS VALUES
(1, 'Marta López', 'Agente'), 
(2, 'Sancho Perez', 'Agente');

INSERT INTO ALOJAMIENTOS VALUES
(1, 'Hotel Sol', 'Málaga', 80.00), 
(2, 'Casa Rural El Encanto', 'Ávila', 65.50), 
(3, 'Apartamentos Vista Mar', 'Valencia', 90.00); 

INSERT INTO RESERVAS VALUES
(1, 1, 1, 1, '2025-04-25', '2025-04-30'), 
(2, 2, 2, 3, '2025-05-01', '2025-05-05'), 
(3, 1, 1, 2, '2025-05-10', '2025-05-12'), 
(4, 3, 1, 3, '2025-06-01', '2025-06-05'), 
(5, 2, 2, 1, '2025-04-15', '2025-04-18'); 


-- EJERCICIO 1
-- Crear un procedimiento que liste todas las reservas junto con el nombre del cliente y del alojamiento. 
DELIMITER //
//
CREATE PROCEDURE MOSTRAR_RESERVAS()
BEGIN
	SELECT R.*,C.NOMBRE,A.NOMBRE
    FROM RESERVAS R
    INNER JOIN CLIENTES C ON C.ID = R.ID_CLIENTE
    INNER JOIN ALOJAMIENTOS A
    ON R.ID_ALOJAMIENTO = A.ID;
END//
DELIMITER ;
CALL MOSTRAR_RESERVAS();

-- 2
DELIMITER //
//
CREATE PROCEDURE SUBIR_PRECIO(P_LOCALIDAD VARCHAR(50))
BEGIN
	UPDATE ALOJAMIENTOS
    SET PRECIO_NOCHE = PRECIO_NOCHE *1.10
    WHERE LOCALIDAD = P_LOCALIDAD;
END//
DELIMITER ;
CALL SUBIR_PRECIO('AVILA');

-- 3
DELIMITER //
//
CREATE PROCEDURE DIAS_RESERVADOS_POR_ALOJAMIENTO()
BEGIN
	SELECT A.NOMBRE, SUM(datediff(R.FECHA_SALIDA, R.FECHA_ENTRADA))
    FROM RESERVAS R
    INNER JOIN ALOJAMIETNOS A ON R.ID_ALOJAMIENTO = A.ID
    GROUP BY A.NOMBRE;
END//
DELIMITER ;
CALL DIAS_RESERVADOS_POR_ALOJAMIENTO();

-- FUNCIONES 
-- 1
-- Crear una función que reciba como parámetro el ID de un cliente y devuelva cuántas reservas ha hecho. 
DELIMITER //
DROP FUNCTION IF EXISTS MOSTRAR_RESERVAS
//
CREATE FUNCTION MOSTRAR_RESERVAS(ID_CLI INT) RETURNS INT
DETERMINISTIC
BEGIN
	DECLARE NUM_RESERVAS INT;
    SELECT count(R.ID) 
    FROM RESERVAS R 
    WHERE ID_CLIENTE = ID_CLI
    INTO NUM_RESERVAS ;
    
    RETURN NUM_RESERVAS;
END
//
DELIMITER ;
SELECT MOSTRAR_RESERVAS(1);

-- Crear una función que calcule el  total de ingresos generados (suma de noches * precio).por un alojamiento cuyo id le pasamos como parámetro 
DELIMITER //
DROP FUNCTION IF EXISTS CALCULAR_INGRESOS
//
CREATE FUNCTION CALCULAR_INGRESOS(ID_ALO INT) RETURNS DECIMAL(6,2)
DETERMINISTIC
BEGIN
	DECLARE INGRESOS DECIMAL(6,2);
    SELECT IFNULL(SUM(DATEDIFF(R.FECHA_SALIDA,R.FECHA_ENTRADA) * A.PRECIO_NOCHE),0) 
    
    FROM ALOJAMIENTOS A INNER JOIN RESERVAS R 
    ON R.ID_ALOJAMIENTO = A.ID
    WHERE A.ID = ID_ALO
    INTO INGRESOS;
    
    RETURN INGRESOS;
END
//
DELIMITER ;
SELECT CALCULAR_INGRESOS(1);

-- Crear una función que devuelva una cadena de texto con el nombre del cliente y número de reservas que ha hecho.
DELIMITER //
DROP FUNCTION IF EXISTS MOSTRAR_RESERVAS_CLI
//
CREATE FUNCTION MOSTRAR_RESERVAS_CLI(ID_CLI INT) RETURNS VARCHAR(100)
DETERMINISTIC
BEGIN
	DECLARE NOM_CLI VARCHAR(100);
	DECLARE NUM_RESERVAS INT;
    
    SELECT NOMBRE
    FROM CLIENTES
    WHERE ID = ID_CLI
    INTO NOM_CLI;
    
    SELECT count(R.ID) 
    FROM RESERVAS R 
    WHERE ID_CLIENTE = ID_CLI
    INTO NUM_RESERVAS;
    
    RETURN CONCAT_WS(' ', NOM_CLI,'ha realizado',NUM_RESERVAS,'reservas');
END//
DELIMITER ;
SELECT MOSTRAR_RESERVAS_CLI(1)

-- Crear una función que devuelve una cadena de texto que dice  si un cliente tiene reservas activas (sin fecha de salida(NULL)). 
DELIMITER //
DROP FUNCTION IF EXISTS MOSTRAR_RESERVAS_CLI
//
CREATE FUNCTION MOSTRAR_RESERVAS_CLI(ID_CLI INT) RETURNS VARCHAR(100)
DETERMINISTIC
BEGIN
	DECLARE NUM_RESERVAS INT;
    DECLARE MENSAJE VARCHAR(100);
    
    SELECT count(R.ID) 
    INTO NUM_RESERVAS 
    FROM RESERVAS R 
    WHERE R.ID_CLIENTE = ID_CLI AND R.FECHA_SALIDA IS NOT NULL;
    
   IF NUM_RESERVAS > 0 THEN
        SET MENSAJE = CONCAT_WS(' ','El cliente', ID_CLI, 'tiene',NUM_RESERVAS, 'reservas activas');
    ELSE
        SET MENSAJE = CONCAT_WS(' ','El cliente', ID_CLI, 'no tiene reservas activas');
    END IF;

    RETURN MENSAJE;
END//
DELIMITER ;
SELECT MOSTRAR_RESERVAS_CLI(1);

CREATE TABLE LOG_CAMBIOS_PRECIO (
ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
ID_ALOJAMIENTO INT,
PRECIO_ANTERIOR DECIMAL(6,2),
PRECIO_NUEVO DECIMAL(6,2),
FECHA_CAMBIO DATETIME);


-- Crear un trigger que registre en una tabla de log cada vez que cambie el precio por noche de un alojamiento. 
DELIMITER //
DROP TRIGGER IF EXISTS REGISTRAR_LOG
//
CREATE TRIGGER REGISTRAR_LOG
BEFORE UPDATE ON ALOJAMIENTOS
FOR EACH ROW
BEGIN
	IF OLD.PRECIO_NOCHE != NEW.PRECIO_NOCHE THEN
	INSERT INTO LOG_CAMBIOS_PRECIO(ID_ALOJAMIENTO,PRECIO_ANTERIOR,PRECIO_NUEVO,FECHA_CAMBIO) 
    VALUES (OLD.ID,OLD.PRECIO_NOCHE,NEW.PRECIO_NOCHE,current_date());
	END IF;
END //
DELIMITER ;

UPDATE ALOJAMIENTOS SET PRECIO_NOCHE = 120 WHERE ID = 2;
SELECT * FROM LOG_CAMBIOS_PRECIO;




-- Crear un trigger que impida insertar reservas cuya fecha de salida sea anterior a la fecha de entrada. -- Utiliza:  SIGNAL SQLSTATE '45000'  
DELIMITER //
DROP TRIGGER IF EXISTS T_FECHAS
//
CREATE TRIGGER T_FECHAS
BEFORE INSERT ON RESERVAS
FOR EACH ROW
BEGIN
	IF NEW.FECHA_SALIDA < NEW.FECHA_ENTRADA THEN
		SIGNAL SQLSTATE'45000'
        SET MESSAGE_TEXT = 'LA FECHA DE SALIDA NO PUEDE SER ANTERIOR A LA DE ENTRADA';
	END IF;
END //
DELIMITER ;

INSERT INTO RESERVAS VALUES
(5, 2, 2, 1, '2025-04-15', '2025-03-18'); 


-- Crear un trigger que impida insertar una reserva duplicada del mismo cliente, alojamiento y fechas. 
DELIMITER //
DROP TRIGGER IF EXISTS T_RESERVA
//
CREATE TRIGGER T_RESERVA
BEFORE INSERT ON RESERVAS
FOR EACH ROW
BEGIN
	DECLARE CONTADOR INT;
    
    SELECT COUNT(*) FROM RESERVAS
    WHERE ID_CLIENTE = NEW.ID_CLIENTE
    AND ID_ALOJAMIENTO = NEW.ID_ALOJAMIENTO
    AND FECHA_ENTRADA = NEW.FECHA_ENTRADA
    AND FECHA_SALIDA = NEW.FECHA_SALIDA
    INTO CONTADOR;
    
	IF CONTADOR > 0 THEN
		SIGNAL SQLSTATE'45000'
        SET MESSAGE_TEXT = 'RESERVA DUPLICADA';
	END IF;
END //
DELIMITER ;

-- Crear un trigger que registre en una tabla de log toda nueva reserva realizada, con nombre de cliente y alojamiento. 
CREATE TABLE LOG_NUEVAS_RESERVAS(
	ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    ID_RESERVA INT,
    CLIENTE VARCHAR(100),
    ALOJAMIENTO VARCHAR(100),
    FECHA_REGISTRO DATE);
    
DELIMITER //
DROP TRIGGER IF EXISTS T_RESERVA
//
CREATE TRIGGER T_RESERVA
AFTER INSERT ON RESERVAS
FOR EACH ROW
BEGIN
	DECLARE NOMBRE_CLI VARCHAR(100);
	DECLARE ALOJAM VARCHAR(100);
    
    SELECT NOMBRE FROM CLIENTES WHERE ID = NEW.ID_CLIENTE INTO NOMBRE_CLI;
    SELECT NOMBRE FROM ALOJAMIENTOS WHERE ID=NEW.ID_ALOJAMIENTO INTO ALOJAM;
    
	INSERT INTO LOG_CAMBIOS_PRECIO(ID_ALOJAMIENTO,PRECIO_ANTERIOR,PRECIO_NUEVO,FECHA_CAMBIO) 
    VALUES (NEW.ID,NOMBRE_CLI,ALOJAM,now());
END //
DELIMITER ;


-- Crear un trigger que  se dispare antes de insertar una fila en la tabla reservas, 
-- impidiendo el  insert cuando el cliente  esté inactivo. 
-- Para hacer el ejercicio, 
-- añade a la tabla de CLIENTES un campo ESTADO de tipo INT, 
-- que valdrá 1 si el cliente está activo o 0 si está inactivo.. 
 -- Pon todos los clientes activos. 
ALTER TABLE CLIENTES
ADD COLUMN ESTADO INT DEFAULT 1;

DELIMITER //
DROP TRIGGER IF EXISTS ACT_RESERVA
//
CREATE TRIGGER ACT_RESERVA
BEFORE INSERT ON RESERVAS
FOR EACH ROW
BEGIN
	DECLARE CONTADOR INT;
    
    SELECT COUNT(*)
    FROM CLIENTES WHERE ID = NEW.ID_CLIENTE AND ESTADO = 0 
    INTO CONTADOR;
    
    IF CONTADOR>0 THEN
    SIGNAL SQLSTATE'45000'
    SET MESSAGE_TEXT = 'EL CLIENTE ESTA INACTIVO';
    END IF;
END //
DELIMITER ;

