-- *************
-- BD DDL1
-- MODULO BBDD 25/26
-- LUCIA ELIZO GOMEZ
-- *************

CREATE DATABASE IF NOT EXISTS CICLISTAS; 
USE CICLISTAS;

CREATE TABLE CICLISTAS (
ID INT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(70),
EDAD INT);

-- DESDE AQUI
CREATE TABLE DIRECTORES (
    ID INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDOS VARCHAR(150),
    ANTIGUEDAD INT
);

CREATE TABLE EQUIPOS (
    ID INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PRESUPUESTO DECIMAL(12,2),
    ID_DIRECTOR INT NOT NULL,
    CONSTRAINT FK_EQUIPOS_DIRECTORES
        FOREIGN KEY (ID_DIRECTOR)
        REFERENCES DIRECTORES(ID)
);

CREATE TABLE PATROCINADORES (
    ID INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    NACIONALIDAD VARCHAR(100)
);

CREATE TABLE CICLISTASEQUIPOS (
    ID_EQUIPO INT NOT NULL,
    ID_CICLISTA INT NOT NULL,
    AÑO_CONTRATO INT,
    CONSTRAINT PK_CICLISTASEQUIPOS
        PRIMARY KEY (ID_EQUIPO, ID_CICLISTA),
    CONSTRAINT FK_CE_EQUIPOS
        FOREIGN KEY (ID_EQUIPO)
        REFERENCES EQUIPOS(ID),
    CONSTRAINT FK_CE_CICLISTAS
        FOREIGN KEY (ID_CICLISTA)
        REFERENCES CICLISTAS(ID)
);

CREATE TABLE PATROCINADOREQUIPOS (
    ID_PATROCINADOR INT NOT NULL,
    ID_EQUIPO INT NOT NULL,
    NACIONALIDAD VARCHAR(100),
    CONSTRAINT PK_PATROCINADOREQUIPOS
        PRIMARY KEY (ID_PATROCINADOR, ID_EQUIPO),
    CONSTRAINT FK_PE_PATROCINADORES
        FOREIGN KEY (ID_PATROCINADOR)
        REFERENCES PATROCINADORES(ID),
    CONSTRAINT FK_PE_EQUIPOS
        FOREIGN KEY (ID_EQUIPO)
        REFERENCES EQUIPOS(ID)
);

ALTER TABLE CICLISTAS
MODIFY APELLIDOS VARCHAR(50);

ALTER TABLE CICLISTAS
MODIFY EDAD INT CHECK (EDAD>=18 AND EDAD <=50);

ALTER TABLE EQUIPOS
MODIFY PRESUPUESTO DECIMAL(12,2) DEFAULT 5000;

ALTER TABLE EQUIPOS
DROP FOREIGN KEY FK_EQUIPOS_DIRECTORES;

ALTER TABLE EQUIPOS
ADD CONSTRAINT FK_EQUIPOS_DIRECTORES
FOREIGN KEY (ID_DIRECTOR)
REFERENCES DIRECTORES(ID)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PATROCINADORES
MODIFY NACIONALIDAD VARCHAR(100) DEFAULT 'ESPAÑOLA';

ALTER TABLE DIRECTORES
MODIFY APELLIDOS VARCHAR(50);

ALTER TABLE DIRECTORES
ADD CONSTRAINT CK_DIRECTORES_ANTIGUEDAD
CHECK (ANTIGUEDAD <= 10);

ALTER TABLE CICLISTASEQUIPOS
DROP FOREIGN KEY FK_CE_EQUIPOS;

ALTER TABLE CICLISTASEQUIPOS
DROP FOREIGN KEY FK_CE_CICLISTAS;

ALTER TABLE CICLISTASEQUIPOS
ADD CONSTRAINT FK_CE_EQUIPOS
FOREIGN KEY (ID_EQUIPO)
REFERENCES EQUIPOS(ID)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE CICLISTASEQUIPOS
ADD CONSTRAINT FK_CE_CICLISTAS
FOREIGN KEY (ID_CICLISTA)
REFERENCES CICLISTAS(ID)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PATROCINADOREQUIPOS
DROP FOREIGN KEY FK_PE_PATROCINADORES;

ALTER TABLE PATROCINADOREQUIPOS
DROP FOREIGN KEY FK_PE_EQUIPOS;

ALTER TABLE PATROCINADOREQUIPOS
ADD CONSTRAINT FK_PE_PATROCINADORES
FOREIGN KEY (ID_PATROCINADOR)
REFERENCES PATROCINADORES(ID)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PATROCINADOREQUIPOS
ADD CONSTRAINT FK_PE_EQUIPOS
FOREIGN KEY (ID_EQUIPO)
REFERENCES EQUIPOS(ID)
ON DELETE CASCADE ON UPDATE CASCADE;