-- *************
-- BASES DE DATOS
-- PRÁCTICA EVALUABLE DDL 
-- MODULO BBDD 25/26
-- LUCIA ELIZO GOMEZ
-- 	BD DAM_DDL_LUCIAELIZOGOMEZ
-- *************

CREATE DATABASE DAM_DDL_LUCIAELIZOGOMEZ;
USE DAM_DDL_LUCIAELIZOGOMEZ;

CREATE TABLE SERIES (
COD_SERIE INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
NOM_SERIE CHAR(50),
GENERO VARCHAR(20) NOT NULL,
FECHA_ESTRENO DATE NOT NULL
);

CREATE TABLE ACTORES (
COD_ACTOR INT PRIMARY KEY,
NOMBRE_ACTOR VARCHAR(50) NOT NULL,
EDAD INT,
NACIONALIDAD VARCHAR(25)
);

CREATE TABLE TEMPORADA (
COD_SERIE INT,
NUM_TEMPORADA INT,
FECHA_ESTRENO DATE,
CONSTRAINT TEMPORADA_PK PRIMARY KEY (COD_SERIE,NUM_TEMPORADA)
);

CREATE TABLE SERIEACTOR (
COD_SERIE INT,
COD_ACTOR INT,
CONSTRAINT SERIEACTOR_PK PRIMARY KEY (COD_SERIE,COD_ACTOR)
);

ALTER TABLE SERIES
ADD CONSTRAINT NOM_SERIE_UK UNIQUE (NOM_SERIE);

ALTER TABLE SERIES 
ADD CONSTRAINT GENERO_CK CHECK (GENERO IN('DRAMA','COMEDIA','FANTASIA','CIENCIA FICCION'));

ALTER TABLE SERIES
RENAME COLUMN FECHA_ESTRENO TO AÑO_ESTRENO;

ALTER TABLE SERIES
MODIFY AÑO_ESTRENO INT NOT NULL;

ALTER TABLE SERIES
RENAME COLUMN NOM_SERIE TO NOMBRE_SERIE;

ALTER TABLE SERIES 
MODIFY NOMBRE_SERIE VARCHAR(100);

ALTER TABLE ACTORES
MODIFY EDAD INT UNSIGNED NOT NULL CHECK(EDAD>0);

ALTER TABLE ACTORES
ADD COLUMN FECHA_NACIMIENTO DATE 
AFTER NOMBRE_ACTOR;

ALTER TABLE ACTORES
MODIFY NACIONALIDAD VARCHAR(25) DEFAULT 'ESPAÑOLA';

ALTER TABLE ACTORES
DROP COLUMN EDAD;

DESC ACTORES;

CREATE TABLE PLATAFORMAS (
COD_PLATAFORMA INT,
NOMBRE_PLATAFORMA VARCHAR(50) NOT NULL
);

ALTER TABLE SERIEACTOR
ADD CONSTRAINT SERIEACTOR_SERIES_FK
	FOREIGN KEY (COD_SERIE)
    REFERENCES SERIES(COD_SERIE)
    ON UPDATE CASCADE ON DELETE CASCADE,
ADD CONSTRAINT SERIEACTOR_ACTORES_FK
	FOREIGN KEY (COD_ACTOR)
    REFERENCES ACTORES(COD_ACTOR)
    ON UPDATE CASCADE ON DELETE CASCADE;
    
ALTER TABLE SERIEACTOR 
MODIFY COD_SERIE INT UNSIGNED;

ALTER TABLE TEMPORADA
MODIFY COD_SERIE INT UNSIGNED;

ALTER TABLE TEMPORADA
ADD CONSTRAINT TEMPORADA_SERIES_FK
	FOREIGN KEY (COD_SERIE)
    REFERENCES SERIES(COD_SERIE);
    
CREATE TABLE SERIEPLATAFORMA (
COD_SERIE INT,
COD_PLATAFORMA INT,
FECHA_INCLUSION DATE NOT NULL,
CONSTRAINT SERIEPLATAFORMA_PK PRIMARY KEY (COD_SERIE,COD_PLATAFORMA)
);

ALTER TABLE SERIEPLATAFORMA
ADD CONSTRAINT SERIEPLATAFORMA_SERIES_FK
	FOREIGN KEY (COD_SERIE)
    REFERENCES SERIES(COD_SERIE)
    ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT SERIEPLATAFORMA_PLATAFORMAS_FK
	FOREIGN KEY (COD_PLATAFORMA)
    REFERENCES PLATAFORMAS(COD_PLATAFORMA);
    
-- COD_SERIE EN SERIEPLATAFORMA ES INCOMPATIBLE CON COD_SERIE EN SERIES, DEBE SER INT UNSIGNED
ALTER TABLE SERIEPLATAFORMA
MODIFY COD_SERIE INT UNSIGNED;

-- ERROR MISSING INDEX: ES NECESARIO AÑADIR RESTRICCION DE CLAVE PRIMARIA EN LA TABLA PLATAFORMAS (COD_PLATAFORMA)
ALTER TABLE PLATAFORMAS
ADD CONSTRAINT PLATAFORMAS_PK PRIMARY KEY (COD_PLATAFORMA);

-- 6.1
ALTER TABLE SERIEPLATAFORMA
ADD CONSTRAINT FECHA_INCLUSION_CK CHECK (year(FECHA_INCLUSION) BETWEEN 2000 AND 2025); 

-- 6.2
ALTER TABLE TEMPORADA
MODIFY FECHA_ESTRENO DATETIME;

-- 6.3
ALTER TABLE ACTORES
RENAME TO PERSONAJES;

-- 6.4
DROP TABLE IF EXISTS SERIEPLATAFORMA;

-- INSERCIONES
-- 1.1
INSERT INTO SERIES VALUES
(NULL, 'SERIE 1', 'DRAMA','2026'),
(NULL, 'SERIE 2', 'COMEDIA','2024');

SELECT*FROM SERIES;

-- 1.2
INSERT INTO PERSONAJES VALUES
(1,'LAURA','2000-09-13',DEFAULT),
(2,'LOLA','1998-08-12',DEFAULT);

SELECT*FROM PERSONAJES;

-- 1.3
INSERT INTO TEMPORADA VALUES
(1,1,'2020-09-13 20:30:09'),
(1,2,'1999-08-12 17:20:02');

-- ACTUALIZACIONES
-- 2.2
UPDATE PERSONAJES
SET NOMBRE_ACTOR = 'LUCIA'
WHERE NOMBRE_ACTOR = 'LOLA';

-- 2.3
UPDATE TEMPORADA
SET FECHA_ESTRENO = '2010-02-03 10:30:19'
WHERE FECHA_ESTRENO = '2020-09-13 20:30:09';

-- BORRADOS
-- 3.1
DELETE FROM SERIES
WHERE COD_SERIE = 1;

ALTER TABLE TEMPORADA 
DROP CONSTRAINT TEMPORADA_SERIES_FK;

DELETE FROM PERSONAJES
WHERE COD_ACTOR = 2;

INSERT INTO SERIES VALUES
(NULL, 'SERIE 1', 'DRAMA','2026');

INSERT INTO TEMPORADA VALUES
(3,1,'2020-09-13 20:30:09');

SELECT*FROM SERIES;

DELETE FROM TEMPORADA
WHERE COD_SERIE = 3;

INSERT INTO PLATAFORMAS VALUES
(1,'NETFLIX');

CREATE TABLE SERIEPLATAFORMA (
COD_SERIE INT,
COD_PLATAFORMA INT,
FECHA_INCLUSION DATE NOT NULL,
CONSTRAINT SERIEPLATAFORMA_PK PRIMARY KEY (COD_SERIE,COD_PLATAFORMA)
);
ALTER TABLE SERIEPLATAFORMA
ADD CONSTRAINT SERIEPLATAFORMA_SERIES_FK
	FOREIGN KEY (COD_SERIE)
    REFERENCES SERIES(COD_SERIE)
    ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT SERIEPLATAFORMA_PLATAFORMAS_FK
	FOREIGN KEY (COD_PLATAFORMA)
    REFERENCES PLATAFORMAS(COD_PLATAFORMA)
    ON DELETE CASCADE ON UPDATE CASCADE;
    
ALTER TABLE SERIEPLATAFORMA
MODIFY COD_SERIE INT UNSIGNED;

ALTER TABLE SERIEPLATAFORMA
ADD CONSTRAINT FECHA_INCLUSION_CK CHECK (year(FECHA_INCLUSION) BETWEEN 2000 AND 2025); 

INSERT INTO SERIEPLATAFORMA VALUES
(2,1,'2000-09-12');

DELETE FROM PLATAFORMAS
WHERE COD_PLATAFORMA = 1;

SELECT*FROM SERIEPLATAFORMA;
-- SE ELIMINA LA FILA QUE CONTIENE ESE COD_PLATAFORMA DEBIDO A LA MODIFICACION Y ELIMINACION EN CASCADA


-- CONSULTAS

CREATE TABLE SERIEPLATAFORMA (
COD_SERIE INT,
COD_PLATAFORMA INT,
FECHA_INCLUSION DATE NOT NULL,
CONSTRAINT SERIEPLATAFORMA_PK PRIMARY KEY (COD_SERIE,COD_PLATAFORMA)
);
ALTER TABLE SERIEPLATAFORMA
ADD CONSTRAINT SERIEPLATAFORMA_SERIES_FK
	FOREIGN KEY (COD_SERIE)
    REFERENCES SERIES(COD_SERIE)
    ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT SERIEPLATAFORMA_PLATAFORMAS_FK
	FOREIGN KEY (COD_PLATAFORMA)
    REFERENCES PLATAFORMAS(COD_PLATAFORMA)
    ON DELETE CASCADE ON UPDATE CASCADE;
    
ALTER TABLE SERIEPLATAFORMA
MODIFY COD_SERIE INT UNSIGNED;

ALTER TABLE SERIEPLATAFORMA
ADD CONSTRAINT FECHA_INCLUSION_CK CHECK (year(FECHA_INCLUSION) BETWEEN 2000 AND 2025); 

ALTER TABLE TEMPORADA
ADD CONSTRAINT TEMPORADA_SERIES_FK
	FOREIGN KEY (COD_SERIE)
    REFERENCES SERIES(COD_SERIE);
    
-- EJECUTA EL SIGUIENTE CÓDIGO PARA QUE PUEDAS VACIAR LAS TABLAS AUNQUE ESTÉN RELACIONADAS 
-- Y LOS CAMPOS AUTOMÁTICOS SE REINICIEN.

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE SERIES;
TRUNCATE PERSONAJES;
TRUNCATE SERIEACTOR;
TRUNCATE SERIEPLATAFORMA;
TRUNCATE PLATAFORMAS;
TRUNCATE TEMPORADA;

SET FOREIGN_KEY_CHECKS = 1;

-- ------------------------------------------------------------------------
-- INSERT EN TABLAS
-- --------------------------------------------------------------------------

-- SERIES

INSERT INTO SERIES (NOMBRE_SERIE, GENERO, AÑO_ESTRENO)
VALUES
('Mundos Paralelos', 'CIENCIA FICCIÓN', 2020),
('Risas en Casa', 'COMEDIA', 2018),
('El Reino Oculto', 'FANTASÍA', 2019),
('Hospital Central', 'DRAMA', 2005);


-- PERSONAJES (antes ACTORES)

INSERT INTO PERSONAJES 
VALUES
(1, 'Laura Martínez', '1990-04-12', 'ESPAÑOLA'),
(2, 'Carlos Ruiz', '1985-09-20', 'ARGENTINA'),
(3, 'Ana Torres', '1992-01-15', 'MEXICANA'),
(4, 'John Smith', '1980-07-30', 'ESTADOUNIDENSE');

--  TEMPORADAS

INSERT INTO TEMPORADA
VALUES
(1, 1, '2021-01-10 20:00:00'),
(1, 2, '2022-02-15 21:30:00'),
(2, 1, '2018-03-05 19:00:00'),
(3, 1, '2019-10-01 22:00:00'),
(4, 1, '2005-09-15 21:00:00'),
(4, 2, '2006-09-15 21:00:00');

-- SERIEACTOR

INSERT INTO SERIEACTOR (COD_SERIE, COD_ACTOR)
VALUES
(1, 1),
(1, 2),
(2, 3),
(3, 1),
(4, 4);

-- PLATAFORMAS

INSERT INTO PLATAFORMAS (COD_PLATAFORMA, NOMBRE_PLATAFORMA)
VALUES
(1, 'Netflix'),
(2, 'HBO Max'),
(3, 'Amazon Prime Video');

-- SERIEPLATAFORMA

INSERT INTO SERIEPLATAFORMA (COD_SERIE, COD_PLATAFORMA, FECHA_INCLUSION)
VALUES
(1, 1, '2020-05-01'),
(1, 2, '2021-01-01'),
(2, 1, '2019-01-01'),
(3, 3, '2020-10-10'),
(4, 1, '2005-10-01');

SELECT*FROM SERIES;
SELECT*FROM PERSONAJES;
SELECT*FROM SERIEPLATAFORMA;
SELECT*FROM PLATAFORMAS;
SELECT*FROM SERIEACTOR;
SELECT*FROM TEMPORADA;

-- 5.1
SELECT S.NOMBRE_SERIE, P.NOMBRE_ACTOR
FROM SERIES S INNER JOIN SERIEACTOR SA
ON S.COD_SERIE = SA.COD_SERIE
INNER JOIN PERSONAJES P
ON SA.COD_ACTOR = P.COD_ACTOR;

-- 5.2
SELECT S.NOMBRE_SERIE
FROM SERIES S INNER JOIN TEMPORADA T
ON S.COD_SERIE = T.COD_SERIE
GROUP BY T.COD_SERIE
HAVING count(NUM_TEMPORADA) > 1;

-- 5.3
SELECT S.NOMBRE_SERIE
FROM SERIES S INNER JOIN SERIEPLATAFORMA SP
ON S.COD_SERIE = SP.COD_SERIE
INNER JOIN PLATAFORMAS P
ON SP.COD_PLATAFORMA = P.COD_PLATAFORMA
GROUP BY S.NOMBRE_SERIE
HAVING COUNT(P.COD_PLATAFORMA) > 1;

-- 5.4
SELECT P.NOMBRE_ACTOR
FROM SERIES S INNER JOIN SERIEACTOR SA
ON S.COD_SERIE = SA.COD_SERIE
INNER JOIN PERSONAJES P
ON SA.COD_ACTOR = P.COD_ACTOR
WHERE S.GENERO = 'FANTASIA';

-- 5.5
SELECT S.NOMBRE_SERIE
FROM SERIES S
WHERE S.AÑO_ESTRENO > (SELECT AVG(AÑO_ESTRENO) FROM SERIES);

-- 5.6
SELECT DISTINCT S.NOMBRE_SERIE
FROM SERIES S
INNER JOIN TEMPORADA T
ON S.COD_SERIE = T.COD_SERIE
WHERE YEAR(T.FECHA_ESTRENO) > 2021;

-- 5.7
SELECT P.NOMBRE_ACTOR
FROM PERSONAJES P INNER JOIN SERIEACTOR SA
ON P.COD_ACTOR = SA.COD_ACTOR
INNER JOIN SERIES S 
ON SA.COD_SERIE= S.COD_SERIE
INNER JOIN SERIEPLATAFORMA SP
ON S.COD_SERIE = SP.COD_SERIE
INNER JOIN PLATAFORMAS PL
ON SP.COD_PLATAFORMA = PL.COD_PLATAFORMA
WHERE NOMBRE_PLATAFORMA = 'NETFLIX';

-- 5.8
SELECT S.NOMBRE_SERIE
FROM SERIES S INNER JOIN TEMPORADA T
ON S.COD_SERIE = T.COD_SERIE
WHERE T.COD_SERIE IS NULL;

-- 5.9
SELECT S.NOMBRE_SERIE
FROM SERIES S INNER JOIN TEMPORADA T
ON S.COD_SERIE = T.COD_SERIE
WHERE T.FECHA_ESTRENO = (SELECT MAX(FECHA_ESTRENO) FROM TEMPORADA);

-- 5.10
SELECT P.NOMBRE_ACTOR
FROM PERSONAJES P INNER JOIN SERIEACTOR SA
ON P.COD_ACTOR = SA.COD_ACTOR
INNER JOIN SERIES S 
ON SA.COD_SERIE= S.COD_SERIE
INNER JOIN SERIEPLATAFORMA SP
ON S.COD_SERIE = SP.COD_SERIE
INNER JOIN PLATAFORMAS PL
ON SP.COD_PLATAFORMA = PL.COD_PLATAFORMA
GROUP BY  P.COD_ACTOR
HAVING COUNT(DISTINCT PL.COD_PLATAFORMA) > 1;