-- *************
-- BASES DE DATOS
-- EJERCICIO DE REPASO DDL Y DML
-- MODULO BBDD 25/26
-- LUCIA ELIZO GOMEZ
-- BD DATOSALUMNOS CONSULTAS 1 TABLA
-- *************

CREATE DATABASE DATOSALUMNOS;
USE DATOSALUMNOS;

CREATE TABLE ALUMNOS (
    expediente INT PRIMARY KEY,
    nombre VARCHAR(50),
    localidad VARCHAR(50),
    fecha_nac DATE,
    direccion VARCHAR(50),
    curso INT,
    nivel VARCHAR(20),
    faltas INT
);

insert into alumnos values(123456,'Juan Miguel Soler Bakero','Plasencia','1995-10-10','Gran V�a, 2, 4A',1,'CF',15);
insert into alumnos values(654321,'Laura G�mez Fern�ndez','Caceres','1994-05-10','Junterones, 10, 5B',2,'ESO',25);
insert into alumnos values(765432,'Beatriz Mart�nez Hern�ndez','Plasencia','1993-05-05','Plaza Mayor, 6, 3B',3,'ESO',5);
insert into alumnos values(987654,'Diego Mart�n Llorente','Navalmoral','1990-06-03','Diego de la Cierva, 5, 7A',1,'BACHILLERATO',34);
insert into alumnos values(445544,'Juan Francisco Cano Riquelme','C�ceres','1992-07-01','Plaza de Belluga, 3, 4A',4,'ESO',13);
insert into alumnos values(223322,'Raquel Riquelme Rubio','Plasencia','1990-11-23','San Juan, 14, 3B',1,'BACHILLERATO',7);
insert into alumnos values(9988877,'Cristina S�nchez Bermejo','C�ceres','1995-03-19','Torre de Romo, 7',1,'CF',1);
insert into alumnos values(334455,'Pedro Jes�s Rodr�guez Soler','Plasencia','1994-03-10','Camino de Badel, 4',2,'ESO',11);
insert into alumnos values(334400,'Javier Ram�nez Rodr�guez','Plasencia','1993-05-27','Gran V�a, 4, 3A',3,'ESO',0);
insert into alumnos values(993322,'Gema Rubio Colero','C�ceres','1992-09-09','Plaza Fuensanta, 5, 7A',1,'BACHILLERATO',19);
insert into alumnos values(554411,'Joaqu�n Hern�ndez Gonz�lez','Plasencia','1991-12-12','Junterones, 4, 5A',2,'BACHILLERATO',14);

SELECT*
FROM ALUMNOS;

SELECT NOMBRE,LOCALIDAD,FECHA_NAC
FROM ALUMNOS;

SELECT NOMBRE AS 'NOMBRE Y APELLIDOS'
FROM ALUMNOS;

SELECT NOMBRE, FALTAS*2 AS 'FALTAS DE ASISTENCIA'
FROM ALUMNOS;

SELECT*
FROM ALUMNOS
WHERE LOCALIDAD='PLASENCIA';

SELECT*
FROM ALUMNOS
WHERE LOCALIDAD='PLASENCIA' OR LOCALIDAD='NAVALMORAL';

SELECT*
FROM ALUMNOS
WHERE LOCALIDAD='PLASENCIA' AND CURSO=1 AND NIVEL='CF';

SELECT*
FROM ALUMNOS
WHERE LOCALIDAD='PLASENCIA'AND CURSO=2 AND NIVEL='BACHILLERATO' AND FALTAS>=10;

SELECT*
FROM ALUMNOS
WHERE LOCALIDAD='CACERES' OR LOCALIDAD='C�ceres'
ORDER BY NOMBRE DESC;

SELECT*
FROM ALUMNOS
ORDER BY NIVEL DESC, CURSO DESC;

SELECT*
FROM ALUMNOS
WHERE FALTAS>=10 AND (CURSO=1 OR CURSO=2);

SELECT*
FROM ALUMNOS
WHERE FALTAS<=10 AND (CURSO=3 OR CURSO=4) AND LOCALIDAD='NAVALMORAL';

SELECT DISTINCT CURSO
FROM ALUMNOS;

SELECT*
FROM ALUMNOS
WHERE FALTAS!=10 AND CURSO=2 AND NIVEL='ESO';

SELECT* 
FROM ALUMNOS
WHERE NOMBRE LIKE 'B%';

SELECT* 
FROM ALUMNOS
WHERE NOMBRE LIKE '%O' AND (LOCALIDAD='CACERES' OR LOCALIDAD='C�ceres');

SELECT* 
FROM ALUMNOS
WHERE CURSO=1 AND NIVEL='ESO' AND NOMBRE LIKE '_U%';

SELECT*
FROM ALUMNOS
WHERE FALTAS=NULL;

SELECT*
FROM ALUMNOS
WHERE FALTAS BETWEEN 10 AND 20
ORDER BY NOMBRE;

SELECT*
FROM ALUMNOS
WHERE FALTAS BETWEEN 10 AND 20 AND (LOCALIDAD='CACERES' OR LOCALIDAD='C�ceres');

SELECT*
FROM ALUMNOS
WHERE FALTAS BETWEEN 10 AND 20 AND LOCALIDAD='PLASENCIA' AND NIVEL='CF';

SELECT*
FROM ALUMNOS
WHERE FALTAS NOT BETWEEN 10 AND 20;

SELECT*
FROM ALUMNOS
WHERE FECHA_NAC BETWEEN '1993-01-01' AND '1994-12-31'
ORDER BY NOMBRE;

SELECT*
FROM ALUMNOS
WHERE CURSO IN(1 , 2);

SELECT*
FROM ALUMNOS
WHERE CURSO IN(3 , 4) AND LOCALIDAD='NAVALMORAL';

SELECT*
FROM ALUMNOS
WHERE NIVEL IN ('BACHILLERATO' , 'CF') 
ORDER BY CURSO DESC, NOMBRE DESC; 

SELECT*
FROM ALUMNOS
WHERE CURSO IN(1, 2) AND NIVEL!='BACHILLERATO'
ORDER BY NOMBRE;

SELECT* 
FROM ALUMNOS
WHERE NOMBRE LIKE 'J%' AND FALTAS>10 AND NIVEL!='BACHILLERATO'
ORDER BY CURSO, NOMBRE;

SELECT EXPEDIENTE, NOMBRE, CURSO, NIVEL
FROM ALUMNOS
WHERE NIVEL!='BACHILLERATO'
ORDER BY NIVEL, NOMBRE DESC;

SELECT upper(NOMBRE)
FROM ALUMNOS
WHERE LOCALIDAD='NAVALMORAL';

SELECT upper(NOMBRE), lower(LOCALIDAD)
FROM ALUMNOS
ORDER BY LOCALIDAD;

SELECT concat(NOMBRE,LOCALIDAD)
FROM ALUMNOS;

SELECT NOMBRE,length(NOMBRE)
FROM ALUMNOS;

SELECT NOMBRE,character_length(NOMBRE),replace(NOMBRE,' ','') AS 'NOMBRE SIN ESPACIOS',character_length('NOMBRE SIN ESPACIOS')
FROM ALUMNOS;

SELECT NOMBRE, year(FECHA_NAC), month(FECHA_NAC), day(fecha_nac), monthname(FECHA_NAC)
FROM ALUMNOS;

SELECT NOMBRE, YEAR(curdate()) - YEAR(FECHA_NAC) AS EDAD
FROM ALUMNOS; 

SELECT nombre,
extract (year from fecha_nac), extract (month from fecha_nac), extract (day from fecha_nac),
to_char(fecha_nac, 'TMMonth')
FROM alumnos;

