-- *************
-- BASES DE DATOS
-- EJERCICIO DE REPASO DDL Y DML
-- MODULO BBDD 25/26
-- LUCIA ELIZO GOMEZ
-- EJERCICIO DDL4
-- *************

CREATE DATABASE DDL4;
USE DDL4;

CREATE TABLE EMPLEADOS (
DNI CHAR(9),
NOMBRE VARCHAR(10),
APELLIDO1 VARCHAR(15),
APELLIDO2 VARCHAR(15),
DIRECC1 VARCHAR(25),
DIRECC2 VARCHAR(20),
CIUDAD VARCHAR(20),
PROVINCIA VARCHAR(20),
COD_POSTAL CHAR(5),
SEXO CHAR(1),
FECHA_NAC DATE);

CREATE TABLE ESTUDIOS (
EMPLEADO_DNI CHAR(9),
UNIVERSIDAD INT,
AÑO INT,
GRADO VARCHAR(3),
ESPECIALIDAD VARCHAR(20));

CREATE TABLE UNIVERSIDADES (
COD_UNIV INT,
NOMBRE_UNIV VARCHAR(25),
CIUDAD VARCHAR(20),
MUNICIPIO VARCHAR(2),
COD_POSTAL CHAR(5));

CREATE TABLE TRABAJOS (
COD_TRABAJO INT,
NOMBRE_TRAB VARCHAR(20),
SALARIO_MIN DECIMAL(10,2),
SALARIO_MAX DECIMAL(10,2));

CREATE TABLE DEPARTAMENTOS (
COD_DPTO INT,
NOMBRE_DPTO VARCHAR(30),
DPTO_PADRE INT,
PRESUPUESTO DECIMAL(10,2),
PRES_ACTUAL DECIMAL(10,2));

CREATE TABLE HISTORIAL_LABORAL (
DNI_EMPLEADO CHAR(9),
COD_TRABAJO INT,
FECHA_INICIO DATE,
FECHA_FIN DATE,
COD_DPTO INT,
DNI_SUPERVISOR INT);

CREATE TABLE HISTORIAL_SALARIAL (
DNI_EMPLEADO CHAR(9),
SALARIO DECIMAL (10,2),
FECHA_COMIENZO DATE,
FECHA_FIN DATE);

ALTER TABLE EMPLEADOS 
MODIFY NOMBRE VARCHAR(10) NOT NULL,
MODIFY APELLIDO1 VARCHAR(15) NOT NULL;

ALTER TABLE UNIVERSIDADES
MODIFY NOMBRE_UNIV VARCHAR(25) NOT NULL;

ALTER TABLE TRABAJOS
MODIFY NOMBRE_TRAB VARCHAR(20) NOT NULL,
MODIFY SALARIO_MIN DECIMAL(10,2) NOT NULL,
MODIFY SALARIO_MAX DECIMAL(10,2) NOT NULL;

ALTER TABLE DEPARTAMENTOS
MODIFY NOMBRE_DPTO VARCHAR(30) NOT NULL,
MODIFY PRESUPUESTO DECIMAL(10,2) NOT NULL;

ALTER TABLE HISTORIAL_SALARIAL
MODIFY SALARIO DECIMAL(10,2);

ALTER TABLE DEPARTAMENTOS
ADD CONSTRAINT NOMBRE_DPTO_UK
	UNIQUE (NOMBRE_DPTO);
    
ALTER TABLE TRABAJOS
ADD CONSTRAINT NOMBRE_TRAB_UK
	UNIQUE (NOMBRE_TRAB);
    
ALTER TABLE EMPLEADOS
ADD CONSTRAINT EMPLEADOS_PK
	PRIMARY KEY (DNI);
    
ALTER TABLE DEPARTAMENTOS
ADD CONSTRAINT DEPARTAMENTOS_PK
	PRIMARY KEY (COD_DPTO);
    
ALTER TABLE DEPARTAMENTOS
ADD CONSTRAINT DEPARTAMENTOS_FK
	FOREIGN KEY (DPTO_PADRE)
    REFERENCES DEPARTAMENTOS(COD_DPTO);

ALTER TABLE ESTUDIOS
ADD CONSTRAINT ESTUDIOS_PK
	PRIMARY KEY (EMPLEADO_DNI, UNIVERSIDAD, ESPECIALIDAD);

ALTER TABLE UNIVERSIDADES
ADD CONSTRAINT UNIVERSIDADES_PK
	PRIMARY KEY (COD_UNIV);
    
ALTER TABLE ESTUDIOS
ADD CONSTRAINT ESTUDIOS_EMPLEADOS_FK
	FOREIGN KEY (EMPLEADO_DNI)
    REFERENCES EMPLEADOS(DNI),
ADD CONSTRAINT ESTUDIOS_UNIVERSIDADES_FK
	FOREIGN KEY (UNIVERSIDAD)
    REFERENCES UNIVERSIDADES(COD_UNIV);
    
ALTER TABLE HISTORIAL_LABORAL
ADD CONSTRAINT HISTORIAL_LABORAL_PK
	PRIMARY KEY (DNI_EMPLEADO, COD_TRABAJO, FECHA_INICIO);

ALTER TABLE TRABAJOS
ADD CONSTRAINT TRABAJOS_PK
	PRIMARY KEY (COD_TRABAJO);

ALTER TABLE HISTORIAL_LABORAL
MODIFY DNI_SUPERVISOR CHAR(9);

ALTER TABLE HISTORIAL_LABORAL
ADD CONSTRAINT HISTORIAL_LABORAL_EMPLEADOS_FK
	FOREIGN KEY (DNI_EMPLEADO)
    REFERENCES EMPLEADOS(DNI),
ADD CONSTRAINT HISTORIAL_LABORAL_SUPERVISOR_FK
	FOREIGN KEY (DNI_SUPERVISOR)
    REFERENCES EMPLEADOS(DNI),
ADD CONSTRAINT HISTORIAL_LABORAL_TRABAJOS_FK
	FOREIGN KEY (COD_TRABAJO)
    REFERENCES TRABAJOS(COD_TRABAJO),
ADD CONSTRAINT HISTORIAL_LABORAL_DEPARTAMENTOS_FK
	FOREIGN KEY (COD_DPTO)
    REFERENCES DEPARTAMENTOS(COD_DPTO);

ALTER TABLE HISTORIAL_SALARIAL
ADD CONSTRAINT HISTORIAL_SALARIAL_PK
	PRIMARY KEY (DNI_EMPLEADO, SALARIO, FECHA_COMIENZO);
    
ALTER TABLE HISTORIAL_SALARIAL
ADD CONSTRAINT HISTORIAL_SALARIAL_EMPLEADOS_FK
	FOREIGN KEY (DNI_EMPLEADO)
    REFERENCES EMPLEADOS(DNI);
    
INSERT INTO EMPLEADOS VALUES
(123456789,'LUCIA','GOMEZ','GARCIA','D1','C1','PLASENCIA','CC',10600,'M','2000-12-21'),
(523456729,'JORGE','GRIS','MARTIN','D2','C2','PLASENCIA','CC',10600,'H','2020-08-23');

INSERT INTO TRABAJOS VALUES
(1,'PROGRAMADOR',1860.8,2200.4),
(2,'TECNICO',860.3,1200.5);

INSERT INTO UNIVERSIDADES VALUES
(1,'UNIVERSIDAD PUBLICA','PLASENCIA','CC',10600),
(2,'UNIVERSIDAD PRIVADA','PLASENCIA','CC',10600);

