CREATE DATABASE T7;
USE T7;

CREATE TABLE ALUMNOS (
ID_ALUMNO INT PRIMARY KEY,
NOMBRE VARCHAR(20),
POBLACION VARCHAR(30) DEFAULT 'PLASENCIA');

INSERT INTO ALUMNOS
VALUES (1,'ALUMNO1','CACERES');

INSERT INTO ALUMNOS
VALUES (2,'ALUMNO2','CACERES'),
	(3,'ALUMNO3','CACERES');

INSERT INTO ALUMNOS (ID_ALUMNO,NOMBRE)
VALUES (4,'ALUMNO4');

INSERT INTO ALUMNOS (ID_ALUMNO,POBLACION)
VALUES (5,'CC');

INSERT INTO ALUMNOS
VALUES (6,NULL,'CC');

INSERT INTO ALUMNOS
VALUES (7,NULL,DEFAULT);

SELECT*FROM ALUMNOS;

CREATE TABLE ALUMNOS2 (
ID_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(20),
POBLACION VARCHAR(30) DEFAULT 'PLASENCIA');

INSERT INTO ALUMNOS2
VALUES (1,'ALUMNO1','CACERES');

INSERT INTO ALUMNOS2 (POBLACION,NOMBRE)
VALUES ('CC','ALUMNO2');

UPDATE ALUMNOS2 
SET POBLACION='CC';

UPDATE ALUMNOS
SET POBLACION='PLASENCIA'
WHERE POBLACION='PLA';

UPDATE ALUMNOS 
SET NOMBRE='NUEVO NOMBRE',POBLACION='BADAJOZ'
WHERE ID_ALUMNO=5;

UPDATE ALUMNOS
SET NOMBRE='ALUMNO5'
WHERE ID_ALUMNO=5 AND POBLACION='BADAJOZ';

UPDATE ALUMNOS
SET NOMBRE='ALUMNOBADAJOZ'
WHERE ID_ALUMNO=5 OR POBLACION='BADAJOZ';

-- INSTRUCCION DELETE
DELETE FROM ALUMNOS2;

INSERT INTO ALUMNOS2(NOMBRE,POBLACION)
VALUES('ALUMNO1','CACERES');

SELECT*FROM ALUMNOS2;

TRUNCATE ALUMNOS2;

DELETE FROM ALUMNOS
WHERE ID_ALUMNO=7;

DELETE FROM ALUMNOS
WHERE ID_ALUMNO=3 AND POBLACION='PLASENCIA';

CREATE TABLE DEPARTAMENTOS (
ID INT PRIMARY KEY,
NOMBRE VARCHAR(50));

CREATE TABLE EMPLEADOS (
ID INT PRIMARY KEY,
NOMBRE VARCHAR(50),
ID_DEPARTAMENTO INT,
CONSTRAINT EMPLEADOS_DEPARTAMENTOS_FK
	FOREIGN KEY (ID_DEPARTAMENTO)
    REFERENCES DEPARTAMENTOS(ID)
    ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO DEPARTAMENTOS
VALUES (1,'CONTABILIDAD'),
		(2,'RECURSOS HUMANOS'),
        (3,'INFORMATICA');
        
INSERT INTO DEPARTAMENTOS
VALUES (4,'VENTAS');

INSERT INTO EMPLEADOS VALUES
(101,'ANA LOPEZ',1),
(102,'CARLOS MARTIN',4),
(103,'LUCIA GARCIA',2),
(104,'JAVIER PEREZ',3),
(105,'MARIA SERRANO',1);

UPDATE EMPLEADOS
SET ID_DEPARTAMENTO=2 WHERE ID=103;

UPDATE DEPARTAMENTOS
SET ID=20 WHERE ID=2;

SELECT*FROM EMPLEADOS;

DELETE FROM DEPARTAMENTOS
WHERE ID=4;

ALTER TABLE EMPLEADOS
DROP CONSTRAINT EMPLEADOS_DEPARTAMENTOS_FK;

ALTER TABLE EMPLEADOS
ADD CONSTRAINT EMPLEADOS_DEPARTAMENTOS_FK
	FOREIGN KEY (ID_DEPARTAMENTO)
    REFERENCES DEPARTAMENTOS(ID);

UPDATE DEPARTAMENTOS
SET ID=40 WHERE ID=4;

DELETE FROM DEPARTAMENTOS 
WHERE ID=40;

