-- *************
-- BASES DE DATOS
-- PRÁCTICA EVALUABLE DDL 
-- MODULO BBDD 25/26
-- LUCIA ELIZO GOMEZ
-- 	BD MI EMPRESA
-- *************

CREATE DATABASE MI_EMPRESA;
USE MI_EMPRESA;

CREATE TABLE CLIENTES (
CLIENTE_NO INT PRIMARY KEY,
NOMBRE VARCHAR(25),
LOCALIDAD VARCHAR(14),
VENDEDOR_NO INT,
DEBE DECIMAL(9,2),
HABER DECIMAL(9,2),
LIMITE_CREDITO DECIMAL(9,2)
);

CREATE TABLE EMPLEADOS (
EMP_NO INT PRIMARY KEY,
APELLIDO VARCHAR(8),
OFICIO VARCHAR(10),
DIRECTOR INT,
FECHA_ALTA DATE,
SALARIO DECIMAL(6,2),
COMISION DECIMAL(6,2),
DEP_NO INT
);

CREATE TABLE PEDIDOS (
PEDIDO_NO INT PRIMARY KEY,
PRODUCTO_NO INT,
CLIENTE_NO INT,
UNIDADES INT,
FECHA_PEDIDO DATE
);

CREATE TABLE PRODUCTOS (
PRODUCTO_NO INT PRIMARY KEY,
DESCRIPCION VARCHAR(30),
PRECIO_ACTUAL DECIMAL(8,2),
STOCK_DISPONIBLE INT
);

CREATE TABLE DEPARTAMENTOS (
DEP_NO INT PRIMARY KEY,
DNOMBRE VARCHAR(14),
LOCALIDAD VARCHAR(10)
);

-- ##################### INTRODUCCIÓN DE DATOS  EN BBDD MI_EMPRESA######################

-- DEPARTAMENTOS
INSERT INTO DEPARTAMENTOS VALUES(10, 'CONTABILIDAD', 'BARCELONA');
INSERT INTO DEPARTAMENTOS VALUES(20, 'INVESTIGACION', 'VALENCIA');
INSERT INTO DEPARTAMENTOS VALUES(30, 'VENTAS',        'MADRID'); 
INSERT INTO DEPARTAMENTOS VALUES(40, 'PRODUCCION',    'SEVILLA');

-- ## EMPLEADOS
INSERT INTO EMPLEADOS VALUES (7839,'REY',     'PRESIDENTE',NULL,'1981-11-17',6000,   NULL, 10);
INSERT INTO EMPLEADOS VALUES (7698,'GARRIDO', 'DIRECTOR',  7839,'1981-05-01',3850.12,NULL, 30);
INSERT INTO EMPLEADOS VALUES (7782,'MARTINEZ','DIRECTOR',  7839,'1981-06-09',2450,   NULL, 10);
INSERT INTO EMPLEADOS VALUES(7499,'ALONSO',   'VENDEDOR',  7698,'1981-02-23',1400,   400,30);
INSERT INTO EMPLEADOS VALUES (7521,'LOPEZ',   'EMPLEADO',  7782,'1981-05-08',1350.50,NULL,10);      
INSERT INTO EMPLEADOS VALUES (7654,'MARTIN',  'VENDEDOR',  7698,'1981-09-28',1500,   1600, 30);
INSERT INTO EMPLEADOS VALUES (7844,'CALVO',   'VENDEDOR',  7698,'1981-09-08',1800,   0,    30);
INSERT INTO EMPLEADOS VALUES (7876,'GIL',     'ANALISTA',  7782,'1982-05-06',3350,   NULL, 20);
INSERT INTO EMPLEADOS VALUES (7900,'JIMENEZ', 'EMPLEADO',  7782,'1983-03-24',1400,   NULL, 20);	

-- ## CLIENTES
INSERT INTO CLIENTES VALUES (101, 'DISTRIBUCIONES GOMEZ', 'MADRID', 7499, 0,0,5000);
INSERT INTO CLIENTES VALUES (102, 'LOGITRONICA S.L', 'BARCELONA', 7654,0,0,5000);
INSERT INTO CLIENTES VALUES (103, 'INDUSTRIAS LACTEAS S.A.', 'LAS ROZAS', 7844,0,0, 10000);
INSERT INTO CLIENTES VALUES (104, 'TALLERES ESTESO S.A.', 'SEVILLA', 7654, 0, 0, 5000);
INSERT INTO CLIENTES VALUES (105, 'EDICIONES SANZ', 'BARCELONA', 7499, 0,0,5000);
INSERT INTO CLIENTES VALUES (106, 'SIGNOLOGIC S.A.', 'MADRID', 7654,0,0,5000);
INSERT INTO CLIENTES VALUES (107, 'MARTIN Y ASOCIADOS S.L.', 'ARAVACA' , 7844,0,0, 10000);
INSERT INTO CLIENTES VALUES (108, 'MANUFACTURAS ALI S.A.', 'SEVILLA', 7654, 0, 0, 5000);

-- ## PRODUCTOS
INSERT INTO PRODUCTOS VALUES(10,'MESA DESPACHO MOD. GAVIOTA', 550, 50);
INSERT INTO PRODUCTOS VALUES (20, 'SILLA DIRECTOR MOD. BUFALO', 670, 25);
INSERT INTO PRODUCTOS VALUES (30, 'ARMARIO NOGAL DOS PUERTAS', 460, 20);
INSERT INTO PRODUCTOS VALUES (40, 'MESA MODELO UNIÓN',340, 15);
INSERT INTO PRODUCTOS VALUES (50, 'ARCHIVADOR CEREZO',1050, 20);
INSERT INTO PRODUCTOS VALUES (60, 'CAJA SEGURIDAD MOD B222', 280, 15);
INSERT INTO PRODUCTOS VALUES (70, 'DESTRUCTORA DE PAPEL A3',450, 25);
INSERT INTO PRODUCTOS VALUES (80, 'MODULO ORDENADOR MOD. ERGOS', 550, 25);

-- ## PEDIDOS

INSERT INTO PEDIDOS VALUES(1000, 20, 103, 3, '2022-10-06');
INSERT INTO PEDIDOS VALUES(1001, 50, 106, 2, '2022-10-06');
INSERT INTO PEDIDOS VALUES(1002, 10, 101, 4, '2022-10-07');
INSERT INTO PEDIDOS VALUES(1003, 20, 105, 4, '2022-10-16');
INSERT INTO PEDIDOS VALUES(1004, 40, 106, 8, '2022-10-20');
INSERT INTO PEDIDOS VALUES(1005, 30, 105, 2, '2022-10-20');
INSERT INTO PEDIDOS VALUES(1006, 70, 103, 3, '2022-11-03');
INSERT INTO PEDIDOS VALUES(1007, 50, 101, 2, '2022-11-06');
INSERT INTO PEDIDOS VALUES(1008, 10, 106, 6, '2022-11-16');
INSERT INTO PEDIDOS VALUES(1009, 20, 105, 2, '2022-11-26');
INSERT INTO PEDIDOS VALUES(1010, 40, 102, 3, '2022-12-08');
INSERT INTO PEDIDOS VALUES(1011, 30, 106, 2, '2022-12-15');
INSERT INTO PEDIDOS VALUES(1012, 10, 105, 3, '2022-12-06');
INSERT INTO PEDIDOS VALUES(1013, 30, 106, 2, '2022-12-06');
INSERT INTO PEDIDOS VALUES(1014, 20, 101, 4, '2023-01-07');
INSERT INTO PEDIDOS VALUES(1015, 70, 105, 4, '2023-01-16');
INSERT INTO PEDIDOS VALUES(1017, 20, 105, 6, '2023-01-20');

ALTER TABLE EMPLEADOS 
ADD CONSTRAINT FK_EMP_DEP_NO
	FOREIGN KEY (DEP_NO)
    REFERENCES DEPARTAMENTOS(DEP_NO)
    ON UPDATE CASCADE ON DELETE CASCADE;
    
ALTER TABLE EMPLEADOS
ADD CONSTRAINT FK_EMP_DIRECTOR
	FOREIGN KEY (DIRECTOR)
    REFERENCES EMPLEADOS(EMP_NO)
    ON UPDATE CASCADE ON DELETE CASCADE;
    
ALTER TABLE CLIENTES 
ADD CONSTRAINT FK_CLI_EMP_NO
	FOREIGN KEY (VENDEDOR_NO)
    REFERENCES EMPLEADOS(EMP_NO)
    ON DELETE CASCADE ON UPDATE CASCADE;
    
ALTER TABLE PEDIDOS 
ADD CONSTRAINT FK_PEDIDOS_CLIENTE_NO
	FOREIGN KEY (CLIENTE_NO)
    REFERENCES CLIENTES(CLIENTE_NO)
    ON UPDATE CASCADE ON DELETE CASCADE;
    
ALTER TABLE PEDIDOS 
ADD CONSTRAINT FK_PEDIDOS_PRODUCTO_NO
	FOREIGN KEY (PRODUCTO_NO)
    REFERENCES PRODUCTOS(PRODUCTO_NO)
    ON UPDATE CASCADE ON DELETE CASCADE;


-- EJERCICIOS
UPDATE EMPLEADOS
SET COMISION = COMISION + 100
WHERE COMISION < 500 OR COMISION IS NULL;

UPDATE EMPLEADOS
SET DIRECTOR = (SELECT EM.EMP_NO FROM EMPLEADOS EM WHERE APELLIDO = 'GARRIDO')
WHERE (SELECT EMP_NO FROM EMPLEADOS WHERE APELLIDO = 'MARTINEZ');

DELETE FROM EMPLEADOS
WHERE (SELECT EMP_NO FROM EMPLEADOS WHERE APELLIDO = 'MARTINEZ');

UPDATE EMPLEADOS
SET SALARIO = SALARIO + 50
WHERE (SELECT DEP_NO FROM DEPARTAMENTOS WHERE DNOMBRE IN('MADRID','BARCELONA');

CREATE VIEW EMPLEADOS_GARRIDO AS 
SELECT EMP_NO, APELLIDO, SALARIO*14 AS SALARIO_ANUAL 
FROM EMPLEADOS 
WHERE DIRECTOR = ( SELECT EMP_NO FROM EMPLEADOS WHERE APELLIDO ='GARRIDO' ); 

CREATE VIEW RESUMEN_DEP (DEPARTAMENTO, EMPLEADOS, SALARIOS, COMISIONES) AS 
SELECT E.DEP_NO, COUNT(EMP_NO), SUM(SALARIO), SUM(COMISION) 
FROM DEPARTAMENTOS D LEFT JOIN EMPLEADOS E 
ON D.DEP_NO = E.DEP_NO 
GROUP BY E.DEP_NO; 

CREATE VIEW CLIENTES_2  AS 
SELECT CLIENTE_NO, NOMBRE, LOCALIDAD  
FROM CLIENTES; 

CREATE VIEW CLIENTES_2_SEVILLA AS 
SELECT * FROM CLIENTES_2 
WHERE LOCALIDAD LIKE 'SEVILLA';

CREATE VIEW EMPLEADOS_SIN_COMISION AS 
SELECT E.EMP_NO, E.APELLIDO, D.DNOMBRE 
FROM EMPLEADOS E, DEPARTAMENTOS D 
WHERE E.DEP_NO = D.DEP_NO AND E.COMISION IS NULL; 

UPDATE PRODUCTOS 
SET PRECIO_ACTUAL = PRECIO_ACTUAL*0.90 
WHERE PRODUCTO_NO NOT IN (SELECT PRODUCTO_NO   
FROM PEDIDOS      
GROUP BY PRODUCTO_NO ); 

UPDATE EMPLEADOS 
SET SALARIO=SALARIO+50 
WHERE DEP_NO IN (SELECT DEP_NO      
FROM DEPARTAMENTOS      
WHERE LOCALIDAD LIKE 'MADRID' OR LOCALIDAD LIKE 'BARCELONA' ); 

UPDATE EMPLEADOS 
SET SALARIO=SALARIO*1.10 
WHERE EMP_NO = (SELECT VENDEDOR_NO FROM CLIENTES 
WHERE CLIENTE_NO = (SELECT CLIENTE_NO FROM PEDIDOS 
GROUP BY CLIENTE_NO 
ORDER BY SUM(UNIDADES) DESC LIMIT 1));

CREATE VIEW EMPLE_DEP_20 AS 
SELECT * FROM EMPLEADOS
WHERE DEP_NO = 20;

CREATE VIEW V_CLIENTES (CLIENTE, NOMBRE, LOCALIDAD) AS 
SELECT CLIENTE_NO, NOMBRE, LOCALIDAD 
FROM CLIENTES 
WHERE CLIENTE_NO IN (SELECT DISTINCT CLIENTE_NO FROM PEDIDOS GROUP BY CLIENTE_NO); 

CREATE VIEW EMPLEADOS_DIRECTORES (EMPLEADO, APELLIDO, SALARIO_ANUAL) AS 
SELECT EMP_NO, APELLIDO, SALARIO*14  
FROM EMPLEADOS 
WHERE OFICIO = 'DIRECTOR'; 

CREATE VIEW JEFES AS 
SELECT E1.APELLIDO, COALESCE(COUNT(E2.DIRECTOR),0)  
FROM EMPLEADOS E1 LEFT JOIN EMPLEADOS E2 
ON E2.DIRECTOR = E1.EMP_NO 
GROUP BY E1.EMP_NO;