-- ************
-- PRIMERA BASE DE DATOS
-- DAM CURSO 25/26
-- LUCIA ELIZO 
-- ************

CREATE DATABASE IF NOT EXISTS PRUEBA;

DROP DATABASE IF EXISTS PRUEBA;

SHOW DATABASES;

USE PRUEBA;

CREATE TABLE ALUMNOS
(
COD_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
DNI CHAR(9) NOT NULL,
NOMBRE VARCHAR(50)
);

DESCRIBE ALUMNOS;
DESC ALUMNOS;
SHOW COLUMNS FROM ALUMNOS;
EXPLAIN ALUMNOS;

ALTER TABLE ALUM 
RENAME TO ALUMNOS;

SHOW TABLES;

ALTER TABLE ALUMNOS 
ADD POBLACION VARCHAR(40) NOT NULL;

ALTER TABLE ALUMNOS 
ADD APELLIDOS VARCHAR(60) 
AFTER NOMBRE;

ALTER TABLE ALUMNOS 
MODIFY POBLACION VARCHAR(40) NOT NULL 
AFTER COD_ALUMNO; 

ALTER TABLE ALUMNOS
DROP POBLACION;

ALTER TABLE ALUMNOS
MODIFY NOMBRE VARCHAR(30);

ALTER TABLE ALUMNOS
RENAME COLUMN NOMBRE TO NOM_ALUMNO;

DROP TABLE ALUMNOS;

ALTER TABLE ALUMNOS
ADD POBLACION VARCHAR(20) DEFAULT 'PLASENCIA';

INSERT INTO ALUMNOS (DNI,NOMBRE)
VALUES ('333A','PEPE'),('444B','MARIA');

INSERT INTO ALUMNOS (DNI,NOMBRE,POBLACION)
VALUES ('333A','PEPE','CACERES'),('444B','MARIA',DEFAULT);

SELECT*FROM ALUMNOS;

INSERT INTO ALUMNOS (DNI,NOMBRE,POBLACION)
VALUES ('666A',NULL, 'CACERES');

INSERT INTO ALUMNOS (DNI,NOMBRE,POBLACION)
VALUES (NULL,NULL, 'CACERES');

DELETE FROM ALUMNOS
WHERE COD_ALUMNO=4;

ALTER TABLE ALUMNOS
MODIFY DNI VARCHAR(50) NOT NULL UNIQUE;

CREATE TABLE PROFESORES
(
DNI CHAR(9),
NOMBRE VARCHAR(50),
CONSTRAINT PRO_PK PRIMARY KEY(DNI)
);

DESC PROFESORES;

CREATE TABLE MATRICULAS
(
ID_ALUMNO INT,
ID_MODULO INT,
FECHA_MATRICULA DATE
);

ALTER TABLE MATRICULAS
ADD CONSTRAINT MAT_PK PRIMARY KEY(ID_ALUMNO,ID_MODULO);

DESCRIBE MATRICULAS;

ALTER TABLE ALUMNOS
RENAME COLUMN COD_ALUMNO TO ID_ALUMNO;

ALTER TABLE MATRICULAS
ADD CONSTRAINT ALU_FK FOREIGN KEY(ID_ALUMNO)
REFERENCES ALUMNOS(ID_ALUMNO) 
ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE MODULOS
(
ID_MODULO INT,
NOMBRE VARCHAR(50)
);

ALTER TABLE MATRICULAS
ADD CONSTRAINT MOD_FK FOREIGN KEY(ID_MODULO)
REFERENCES MODULOS(ID_MODULO) 
ON UPDATE CASCADE ON DELETE CASCADE;