-- *************
-- BD DDL1
-- MODULO BBDD 25/26
-- LUCIA ELIZO GOMEZ
-- PRACTICA ORGANIZACION
-- *************

CREATE DATABASE ORGANIZACION;
USE ORGANIZACION;

CREATE TABLE EMPLEADOS (
NUM_EMPLEADO INT PRIMARY KEY,
APELLIDO VARCHAR(50),
OFICIO VARCHAR(50),
DIRECCION VARCHAR(50),
FECHA_ALTA DATE,
SALARIO DECIMAL(10,2),
COMISION DECIMAL(4,2),
NUM_DPTO INT);

CREATE TABLE DEPARTAMENTO (
NUM_DPTO INT PRIMARY KEY,
NOMBRE VARCHAR(50),
LOCALIDAD VARCHAR(50));

ALTER TABLE EMPLEADOS
MODIFY NUM_DPTO INT NOT NULL;

ALTER TABLE EMPLEADOS
ADD CONSTRAINT EMPLEADOS_UK
	UNIQUE (APELLIDO);
    
ALTER TABLE EMPLEADOS
ADD CONSTRAINT SALARIO
	CHECK (SALARIO>0);
    
ALTER TABLE EMPLEADOS 
ADD CONSTRAINT COMISION2
	CHECK (COMISION BETWEEN 2 AND 15);

ALTER TABLE EMPLEADOS
DROP CONSTRAINT EMPLEADOS_UK;

ALTER TABLE EMPLEADOS
ADD CONSTRAINT EMPLEADOS_DEPARTAMENTO_FK
	FOREIGN KEY (NUM_DPTO)
    REFERENCES DEPARTAMENTO(NUM_DPTO)
    ON UPDATE CASCADE ON DELETE CASCADE;

INSERT INTO EMPLEADOS
VALUES (1,'LOPEZ','TECNICO','D1','1999-07-23',8.3,DEFAULT,10),
		(2,'MARTIN','EMPLEADO','D2','1998-04-03',8.2,DEFAULT,20),
        (3,'BLASCO','TECNICO','D3','1989-01-20',7.4,DEFAULT,10),
        (4,'GOMEZ','EMPLEADO','D4','1983-09-15',3.9,DEFAULT,40),
        (5,'GARCIA','TECNICO','D5','2001-11-23',5.3,DEFAULT,30);

ALTER TABLE EMPLEADOS
MODIFY COMISION DECIMAL DEFAULT 10; 

ALTER TABLE DEPARTAMENTO 
MODIFY NOMBRE VARCHAR(50) NOT NULL,
MODIFY LOCALIDAD VARCHAR(50) NOT NULL;

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT LOCALIDAD
	CHECK (LOCALIDAD IN('SEVILLA', 'MADRID', 'BARCELONA', 'BILBAO'));

INSERT INTO DEPARTAMENTO VALUES
(10,'CONTABILIDAD','SEVILLA'),
(20,'INVESTIGACION','MADRID'),
(30,'VENTAS','BARCELONA'),
(40,'PRODUCCION','BILBAO');

SELECT*FROM DEPARTAMENTO;
DESC DEPARTAMENTO;

CREATE TABLE TIENDAS (
DNI INT(9),
NOMBRE VARCHAR(50),
DIRECCION VARCHAR(100),
POBLACION VARCHAR(50),
PROVINCIA VARCHAR(25),
CODPOSTAL CHAR(5));

ALTER TABLE TIENDAS 
ADD CONSTRAINT TIENDAS_PK
	PRIMARY KEY (DNI),
MODIFY NOMBRE VARCHAR(30) NOT NULL,
MODIFY PROVINCIA VARCHAR(25) DEFAULT 'CACERES',
MODIFY CODPOSTAL CHAR(5) NOT NULL;

INSERT INTO TIENDAS VALUES
(123456789,'LUCIA','C1','PLA',DEFAULT,10600),
(543216789,'SEBAS','C2','PLASENCIA',DEFAULT,10630),
(123459876,'MARIA','C3','PLASENCIA',DEFAULT,10610),
(987654321,'LUCAS','C4','PLA',DEFAULT,10600),
(123736489,'LUZ','C5','PLASEN',DEFAULT,10608);

SELECT*FROM TIENDAS;
DESC TIENDAS;

UPDATE TIENDAS
SET CODPOSTAL=10000;

DELETE FROM TIENDAS
WHERE NOMBRE='LUCAS';

ALTER TABLE TIENDAS
DROP DIRECCION;

CREATE INDEX APELLIDO_1 ON EMPLEADOS(APELLIDO);

SELECT*FROM EMPLEADOS;
DESC EMPLEADOS;