-- *************
-- BD DDL1
-- MODULO BBDD 25/26
-- LUCIA ELIZO GOMEZ
-- *************
-- Crea la base de datos DDL1, que tendrá las siguientes tablas:
-- CLIENTE

CREATE DATABASE DDL1;

USE DDL1;

CREATE TABLE CLIENTE
(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(25),
PRIMER_APELLIDO VARCHAR(15) NOT NULL,
CIUDAD VARCHAR(100),
CATEGORIA INT
);

-- COMERCIAL

CREATE TABLE COMERCIAL
(
ID INT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO1 VARCHAR(100) NOT NULL,
APELLIDO2 VARCHAR(100),
CIUDAD VARCHAR(100),
COMISION FLOAT
);

ALTER TABLE CLIENTE
MODIFY COLUMN NOMBRE VARCHAR(100) NOT NULL;

DESCRIBE CLIENTE;

ALTER TABLE CLIENTE
RENAME COLUMN PRIMER_APELLIDO TO APELLIDO1;

ALTER TABLE CLIENTE
MODIFY APELLIDO1 VARCHAR(100) NOT NULL;

ALTER TABLE CLIENTE
ADD APELLIDO2 VARCHAR(100)
AFTER APELLIDO1;

ALTER TABLE CLIENTE
DROP COLUMN CATEGORIA;

ALTER TABLE COMERCIAL
MODIFY COMISION FLOAT DEFAULT '10';

DESCRIBE COMERCIAL;

CREATE TABLE ALUMNOS
(
DNI CHAR(9),
NOMBRE VARCHAR(50),
TELEFONO CHAR(9)
);

ALTER TABLE ALUMNOS
ADD CONSTRAINT ALU_PK PRIMARY KEY(DNI);

ALTER TABLE ALUMNOS
ADD CONSTRAINT ALU_UK UNIQUE(TELEFONO);

ALTER TABLE ALUMNOS
MODIFY NOMBRE VARCHAR(100) NOT NULL;

DESC ALUMNOS;

INSERT INTO COMERCIAL
VALUES ('1','PEPE','MARTINEZ','MARTINEZ','PLASENCIA',DEFAULT);

SELECT*FROM COMERCIAL;