-- *************
-- BD DDL1
-- MODULO BBDD 25/26
-- LUCIA ELIZO GOMEZ
-- *************

CREATE DATABASE PRACTICA2;
USE PRACTICA2;

CREATE TABLE ESTUDIANTES (
ESTUDIANTE_ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100),
CORREO VARCHAR(25) UNIQUE,
FECHA_NACIMIENTO DATE,
ACTIVO BOOLEAN);

CREATE TABLE INSTRUCTORES (
INSTRUCTOR_ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100),
ESPECIALIDAD VARCHAR(50),
SALARIO FLOAT);

CREATE TABLE CURSOS (
CURSO_ID INT AUTO_INCREMENT PRIMARY KEY,
TITULO VARCHAR(150),
DESCRIPCION VARCHAR(500),
FECHA_INICIO DATE,
FECHA_FIN DATE,
INSTRUCTOR_ID INT, 
CONSTRAINT INS_FK FOREIGN KEY (INSTRUCTOR_ID)
REFERENCES INSTRUCTORES(INSTRUCTOR_ID)
ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE INSCRIPCIONES (
INSCRIPCION_ID INT AUTO_INCREMENT PRIMARY KEY,
ESTUDIANTE_ID INT,
CONSTRAINT ES_FK FOREIGN KEY (ESTUDIANTE_ID)
REFERENCES ESTUDIANTES(ESTUDIANTE_ID)
ON UPDATE CASCADE ON DELETE CASCADE,
CURSO_ID INT,
CONSTRAINT CUR_FK FOREIGN KEY (CURSO_ID)
REFERENCES CURSOS(CURSO_ID)
ON UPDATE CASCADE ON DELETE CASCADE,
FECHA_INSCRIPCION DATE);

DESC CURSOS;

-- AÑADIR COLUMNA
ALTER TABLE ESTUDIANTES ADD TELEFONO CHAR(9);

-- ELIMINAR COLUMNA
ALTER TABLE CURSOS DROP DESCRIPCION;

-- MODIFICAR DATO
ALTER TABLE INSTRUCTORES MODIFY SALARIO DECIMAL(10,3);

-- AÑADIR RESTRICCION
ALTER TABLE INSTRUCTORES ADD CONSTRAINT SALARIO_CK CHECK (SALARIO>0);

-- ELIMINAR RESTRICCION
ALTER TABLE INSCRIPCIONES DROP CONSTRAINT CUR_FK;

-- RENOMBRAR COLUMNA
ALTER TABLE ESTUDIANTES RENAME COLUMN CORREO TO EMAIL;

-- RENOMBRAR TABLA
RENAME TABLE INSCRIPCIONES TO MATRICULAS;

-- AÑADIR CLAVE FORANEA
CREATE TABLE CATEGORIAS (
CATEGORIA_ID INT PRIMARY KEY,
NOMBRE VARCHAR(20),
DESCRIPCION VARCHAR(50));

ALTER TABLE CURSOS ADD COLUMN CATEGORIA_ID INT;

ALTER TABLE CURSOS ADD CONSTRAINT CAT_FK FOREIGN KEY (CATEGORIA_ID)
REFERENCES CATEGORIAS(CATEGORIA_ID)
ON UPDATE CASCADE ON DELETE CASCADE;

-- ELIMINAR TABLA
DROP TABLE INSTRUCTORES; -- ERROR PORQUE ESTA RELACIONADA CON OTRA TABLA, QUITAR FK.

ALTER TABLE CURSOS DROP CONSTRAINT INS_FK;

-- AÑADIRI COLUMNA
ALTER TABLE CURSOS ADD COLUMN DURACION INT 
AS (datediff(FECHA_FIN, FECHA_INICIO));

ALTER TABLE CURSOS ADD COLUMN DURACION INT 
