-- USO DELIMITADORES

DROP DATABASE IF EXISTS EJEMPLOS_RUTINAS;
CREATE DATABASE EJEMPLOS_RUTINAS;
USE EJEMPLOS_RUTINAS;

DELIMITER //
DROP PROCEDURE IF EXISTS EJEMPLO1//
CREATE PROCEDURE EJEMPLO1()
BEGIN
	SELECT "ESTO ES UN EJEMPLO DE PROCEDIMIENTO"
    AS MENSAJE;
END;
//
DELIMITER ;

CALL EJEMPLO1();
DROP PROCEDURE EJEMPLO1;

-- USO VARIABLES
SET @MIVARIABLE='EJEMPLO VARIABLE GLOBAL';

SELECT @MIVARIABLE;

DELIMITER //
//
CREATE PROCEDURE VAR_EJEMPLO1()
BEGIN
	DECLARE VARIABLE1 INT;
    DECLARE VARIABLE2 VARCHAR(20);
    SET VARIABLE1=25;
    SET VARIABLE2='ESTO ES UNA PRUEBA';
    SELECT concat_ws('*****', VARIABLE1, VARIABLE2) AS RESULTADO;
    SELECT CONCAT(VARIABLE1, '------', VARIABLE2) AS RESULTADO2;
END;
//
DELIMITER ;

CALL VAR_EJEMPLO1();

CREATE TABLE ALUMNOS (
ID INT PRIMARY KEY,
NOMBRE VARCHAR(20)
);

INSERT INTO ALUMNOS VALUES
(1,'ALUMNO1'),
(2,'ALUMNO2'),
(3,'ALUMNO3'),
(4,'ALUMNO4');

-- SELECT... INTO... (SET VARIABLES CON EL VALOR DE LAS COLUMNAS)

DELIMITER //
//
CREATE PROCEDURE IMPRIMIR_NUMEROS_REPEAT()
BEGIN
	DECLARE CONTADOR INT DEFAULT 1;
    DECLARE RESULTADO VARCHAR(255) DEFAULT '';
    REPEAT
		SET RESULTADO = CONCAT(RESULTADO,CONTADOR,' ');
        SET CONTADOR = CONTADOR + 1;
	UNTIL CONTADOR > 10
    END REPEAT;
    SELECT RESULTADO AS NUMEROS;
END;//
DELIMITER ;

CALL IMPRIMIR_NUMEROS_REPEAT();

DELIMITER //
//
CREATE PROCEDURE IMPRIMIR_NUMEROS_WHILE()
BEGIN
	DECLARE CONTADOR INT DEFAULT 1;
    DECLARE RESULTADO VARCHAR(255) DEFAULT '';
    WHILE CONTADOR > 10 DO
		SET RESULTADO = CONCAT(RESULTADO,CONTADOR,' ');
        SET CONTADOR = CONTADOR + 1;
    END WHILE;
    SELECT RESULTADO AS NUMEROS;
END;//
DELIMITER ;

CALL IMPRIMIR_NUMEROS_WHILE();

-- FUNCIONES

SET GLOBAL log_bin_trust_function_creators = 1;

DELIMITER //
DROP FUNCTION IF EXISTS EJEMPLO_FUNCION
//
CREATE FUNCTION EJEMPLO_FUNCION() 
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
	RETURN 'ESTO ES UN EJEMPLO DE FUNCION';
END//
DELIMITER ;

SELECT EJEMPLO_FUNCION();

DELIMITER //
DROP FUNCTION IF EXISTS EJEMPLO_FUNCION2
//
CREATE FUNCTION EJEMPLO_FUNCION2(NUM1 INT, NUM2 INT) 
RETURNS INT
DETERMINISTIC
BEGIN
	RETURN NUM1+NUM2;
END//
DELIMITER ;

SELECT EJEMPLO_FUNCION2(5,25);

CREATE TABLE productos (    id INT AUTO_INCREMENT PRIMARY KEY,    nombre VARCHAR(20) NOT NULL,    coste FLOAT NOT NULL DEFAULT 0.0,    precio FLOAT NOT NULL DEFAULT 0.0    );

INSERT INTO productos (nombre, coste, precio) VALUES ('Producto A', 4, 8), ('Producto B', 1, 1.5), ('Producto C', 50, 80);

DELIMITER //
DROP FUNCTION IF EXISTS CALCULAR_BENEFICIO
//
CREATE FUNCTION CALCULAR_BENEFICIO(COSTE FLOAT, PRECIO FLOAT) RETURNS FLOAT
DETERMINISTIC
BEGIN
	DECLARE BENEFICIO FLOAT;
    SET BENEFICIO = PRECIO-COSTE;
    RETURN BENEFICIO;
END
//
DELIMITER ;
SELECT CALCULAR_BENEFICIO(20,30);

SELECT *, CALCULAR_BENEFICIO(COSTE, PRECIO)
FROM PRODUCTOS;

DELIMITER // 
DROP FUNCTION IF EXISTS CUENTA_PRODUCTOS
// 
CREATE FUNCTION CUENTA_PRODUCTOS() RETURNS INT 
DETERMINISTIC 
BEGIN 
	DECLARE NUM_PRODUCTOS INT; 
    SELECT COUNT(*) FROM PRODUCTOS  
    INTO NUM_PRODUCTOS; 
RETURN NUM_PRODUCTOS; 
END; // 
DELIMITER ;

-- CURSORES
CREATE TABLE TABLA1 (ID1 INT PRIMARY KEY, DATO1 INT);
CREATE TABLE TABLA2 (ID2 INT PRIMARY KEY, DATO2 INT);
CREATE TABLE TABLA3 (ID3 INT PRIMARY KEY, DATO3 INT);

INSERT INTO TABLA1 VALUES (1,7);
INSERT INTO TABLA1 VALUES (2,8);
INSERT INTO TABLA1 VALUES (3,15);

CREATE TABLE TABLA_RESULTADO(ID_R INT, DATO_R INT);

DELIMITER // 
DROP PROCEDURE IF EXISTS CURSORES1
// 
CREATE PROCEDURE CURSORES1 () 
BEGIN 
	DECLARE FIN_TABLA INT DEFAULT 0;
    DECLARE VAR_ID1 INT;
	DECLARE VAR_DATO1 INT;
	DECLARE CUR1 CURSOR FOR SELECT ID1,DATO1 FROM TABLA1;
    DECLARE CONTINUE HANDLER FOR SQLSTATE'02000'
    SET FIN_TABLA = 1;
    
    OPEN CUR1;
    REPEAT
		FETCH CUR1 INTO VAR_ID1,VAR_DATO1;
		IF NOT FIN_TABLA THEN
			IF VAR_DATO1 > 10 THEN
				INSERT INTO TABLA_RESULTADO VALUES (VAR_DATO1, VAR_ID1);
			ELSE
				INSERT INTO TABLA_RESULTADO VALUES (0,0);
			END IF;
		END IF;
	UNTIL FIN_TABLA
    END REPEAT;
    CLOSE CUR1;
    select*from tabla_resultado;
END;
//
DELIMITER ;

CALL CURSORES1();