-- *************
-- BASES DE DATOS
-- EJERCICIO DE REPASO DDL Y DML
-- MODULO BBDD 25/26
-- LUCIA ELIZO GOMEZ
-- BD PROGRAMACION
-- *************

CREATE DATABASE PROGRAMACION2;
USE PROGRAMACION2;

CREATE TABLE FABRICANTE (
ID_FAB INT PRIMARY KEY,
NOMBRE VARCHAR(50),
PAIS VARCHAR(30));

CREATE TABLE COMERCIO (
CIF INT PRIMARY KEY,
NOMBRE VARCHAR(50),
CIUDAD VARCHAR(50));

CREATE TABLE CLIENTE (
DNI INT PRIMARY KEY,
NOMBRE VARCHAR(50),
EDAD INT);

CREATE TABLE DESARROLLA (
ID_FAB INT,
CODIGO INT,
CONSTRAINT DESARROLLA_PK
	PRIMARY KEY (ID_FAB,CODIGO));

CREATE TABLE DISTRIBUYE (
CIF INT,
CODIGO INT,
CANTIDAD INT,
CONSTRAINT DISTRIBUYE_PK
	PRIMARY KEY (CIF,CODIGO));

CREATE TABLE REGISTRA (
CIF INT,
DNI INT,
CODIGO INT,
CONSTRAINT REGISTRA_PK
	PRIMARY KEY (CIF,DNI,CODIGO));
    
CREATE TABLE PROGRAMA (
CODIGO INT PRIMARY KEY,
NOMBRE VARCHAR(50),
VERSION VARCHAR(50));

ALTER TABLE DESARROLLA
ADD CONSTRAINT DESARROLLA_FABRICANTE_FK
	FOREIGN KEY (ID_FAB)
    REFERENCES FABRICANTE(ID_FAB);
    
ALTER TABLE DESARROLLA
ADD CONSTRAINT DESARROLLA_PROGRAMA_FK
	FOREIGN KEY (CODIGO)
    REFERENCES PROGRAMA(CODIGO);

ALTER TABLE DISTRIBUYE
ADD CONSTRAINT DISTRIBUYE_COMERCIO_FK
	FOREIGN KEY (CIF)
    REFERENCES COMERCIO(CIF);
    
ALTER TABLE DISTRIBUYE
ADD CONSTRAINT DISTRIBUYE_PROGRAMA_FK
	FOREIGN KEY (CODIGO)
    REFERENCES PROGRAMA(CODIGO);
    
ALTER TABLE REGISTRA
ADD CONSTRAINT REGISTRA_COMERCIO_FK
	FOREIGN KEY (CIF)
    REFERENCES COMERCIO(CIF);
    
ALTER TABLE REGISTRA
ADD CONSTRAINT REGISTRA_CLIENTE_FK
	FOREIGN KEY (DNI)
    REFERENCES CLIENTE(DNI);
    
ALTER TABLE REGISTRA
ADD CONSTRAINT REGISTRA_PROGRAMA_FK
	FOREIGN KEY (CODIGO)
    REFERENCES PROGRAMA(CODIGO);
    

INSERT INTO fabricante VALUES (1,'Oracle','Estados Unidos');
INSERT INTO fabricante VALUES (2,'Microsoft','Estados Unidos');
INSERT INTO fabricante VALUES (3,'IBM','Estados Unidos');
INSERT INTO fabricante VALUES (4,'Dinamic','Espa�a');
INSERT INTO fabricante VALUES (5,'Borland','Estados Unidos');
INSERT INTO fabricante VALUES (6,'Symantec','Estados Unidos');

INSERT INTO programa VALUES (1,'Application Server','9i');
INSERT INTO programa VALUES (2,'Oracle Database','8i');
INSERT INTO programa VALUES (3,'Database','9i');
INSERT INTO programa VALUES (4,'Database','10g');
INSERT INTO programa VALUES (5,'Developer','6i');
INSERT INTO programa VALUES (6,'Access','97');
INSERT INTO programa VALUES (7,'Access','2000');
INSERT INTO programa VALUES (8,'Access','XP');
INSERT INTO programa VALUES (9,'Windows','98');
INSERT INTO programa VALUES (10,'Windows','XP Professional');
INSERT INTO programa VALUES (11,'Windows','XP Home Edition');
INSERT INTO programa VALUES (12,'Windows','2003 Server');
INSERT INTO programa VALUES (13,'Norton Internet Security','2004');
INSERT INTO programa VALUES (14,'Freddy Hardest',NULL);
INSERT INTO programa VALUES (15,'Paradox','2');
INSERT INTO programa VALUES (16,'C++ Builder','5.5');
INSERT INTO programa VALUES (17,'DB/2','2.0');
INSERT INTO programa VALUES (18,'OS/2','1.0');
INSERT INTO programa VALUES (19,'JBuilder','X');
INSERT INTO programa VALUES (20,'La prisi�n','1.0');

INSERT INTO comercio VALUES (1,'El Corte Ingl�s','Sevilla');
INSERT INTO comercio VALUES (2,'El Corte Ingl�s','Madrid');
INSERT INTO comercio VALUES (3,'Jump','Valencia');
INSERT INTO comercio VALUES (4,'Centro Mail','Sevilla');
INSERT INTO comercio VALUES (5,'FNAC','Barcelona');

INSERT INTO cliente VALUES (1,'Pepe P�rez',45);
INSERT INTO cliente VALUES (2,'Juan Gonz�lez',45);
INSERT INTO cliente VALUES (3,'Mar�a G�mez',33);
INSERT INTO cliente VALUES (4,'Javier Casado',18);
INSERT INTO cliente VALUES (5,'Nuria S�nchez',29);
INSERT INTO cliente VALUES (6,'Antonio Navarro',58);

INSERT INTO desarrolla VALUES (1,1);
INSERT INTO desarrolla VALUES (1,2);
INSERT INTO desarrolla VALUES (1,3);
INSERT INTO desarrolla VALUES (1,4);
INSERT INTO desarrolla VALUES (1,5);
INSERT INTO desarrolla VALUES (2,6);
INSERT INTO desarrolla VALUES (2,7);
INSERT INTO desarrolla VALUES (2,8);
INSERT INTO desarrolla VALUES (2,9);
INSERT INTO desarrolla VALUES (2,10);
INSERT INTO desarrolla VALUES (2,11);
INSERT INTO desarrolla VALUES (2,12);
INSERT INTO desarrolla VALUES (6,13);
INSERT INTO desarrolla VALUES (4,14);
INSERT INTO desarrolla VALUES (5,15);
INSERT INTO desarrolla VALUES (5,16);
INSERT INTO desarrolla VALUES (3,17);
INSERT INTO desarrolla VALUES (3,18);
INSERT INTO desarrolla VALUES (5,19);
INSERT INTO desarrolla VALUES (4,20);

INSERT INTO distribuye VALUES (1,1,10);
INSERT INTO distribuye VALUES (1,2,11);
INSERT INTO distribuye VALUES (1,6,5);
INSERT INTO distribuye VALUES (1,7,3);
INSERT INTO distribuye VALUES (1,10,5);
INSERT INTO distribuye VALUES (1,13,7);
INSERT INTO distribuye VALUES (2,1,6);
INSERT INTO distribuye VALUES (2,2,6);
INSERT INTO distribuye VALUES (2,6,4);
INSERT INTO distribuye VALUES (2,7,7);
INSERT INTO distribuye VALUES (3,10,8);
INSERT INTO distribuye VALUES (3,13,5);
INSERT INTO distribuye VALUES (4,14,3);
INSERT INTO distribuye VALUES (4,20,6);
INSERT INTO distribuye VALUES (5,15,8);
INSERT INTO distribuye VALUES (5,16,2);
INSERT INTO distribuye VALUES (5,17,3);
INSERT INTO distribuye VALUES (5,19,6);

INSERT INTO distribuye VALUES (5,8,8);

INSERT INTO registra VALUES (1,1,1,'Internet');
INSERT INTO registra VALUES (1,3,4,'Tarjeta postal');
INSERT INTO registra VALUES (4,2,10,'Tel�fono');
INSERT INTO registra VALUES (4,1,10,'Tarjeta postal');
INSERT INTO registra VALUES (5,2,12,'Internet');
INSERT INTO registra VALUES (2,4,15,'Internet');

ALTER TABLE REGISTRA
ADD COLUMN MEDIO VARCHAR(20);

SELECT DNI, NOMBRE
FROM CLIENTE;

SELECT *
FROM PROGRAMA;

SELECT DISTINCT C.CIUDAD
FROM COMERCIO C INNER JOIN DISTRIBUYE D INNER JOIN PROGRAMA P
ON C.CIF=D.CIF AND D.CODIGO=P.CODIGO;

SELECT DISTINCT NOMBRE
FROM PROGRAMA;

SELECT * 
FROM FABRICANTE
WHERE PAIS NOT IN('ESPA�A');

SELECT VERSION, CODIGO
FROM PROGRAMA
WHERE NOMBRE='WINDOWS';

SELECT NOMBRE
FROM COMERCIO
WHERE NOMBRE!='EL CORTE INGL�S';

SELECT *
FROM PROGRAMA
WHERE NOMBRE IN('WINDOWS','ACCESS');

SELECT NOMBRE, EDAD
FROM CLIENTE
WHERE EDAD BETWEEN 10 AND 25 OR EDAD>50;

SELECT DISTINCT NOMBRE, CIUDAD
FROM COMERCIO
WHERE CIUDAD IN('SEVILLA','MADRID');

SELECT NOMBRE
FROM CLIENTE
WHERE NOMBRE LIKE '%O' AND EDAD>30;

SELECT *
FROM PROGRAMA
WHERE VERSION LIKE '%I' OR NOMBRE LIKE 'A%' OR NOMBRE LIKE 'W%';

SELECT *
FROM PROGRAMA
WHERE VERSION LIKE '%I' OR NOMBRE LIKE 'A%S';

SELECT *
FROM PROGRAMA
WHERE VERSION LIKE '%I' OR NOMBRE NOT LIKE 'A%';

SELECT *
FROM COMERCIO
ORDER BY NOMBRE DESC;

SELECT *
FROM PROGRAMA
ORDER BY VERSION;

SELECT P.*, F.NOMBRE
FROM PROGRAMA P INNER JOIN DESARROLLA D INNER JOIN FABRICANTE F
ON P.CODIGO=D.CODIGO AND F.ID_FAB = D.ID_FAB
WHERE F.NOMBRE='ORACLE';

SELECT C.*, P.*
FROM COMERCIO C INNER JOIN DISTRIBUYE D INNER JOIN PROGRAMA P
ON C.CIF=D.CIF AND D.CODIGO=P.CODIGO
WHERE P.NOMBRE='WINDOWS';

SELECT C.*, P.*, D.CANTIDAD
FROM COMERCIO C INNER JOIN DISTRIBUYE D INNER JOIN PROGRAMA P
ON C.CIF=D.CIF AND D.CODIGO=P.CODIGO
WHERE C.NOMBRE='EL CORTE INGL�S' AND C.CIUDAD='MADRID';

SELECT P.*, F.NOMBRE AS 'NOMBRE FABRICANTE'
FROM PROGRAMA P INNER JOIN DESARROLLA D INNER JOIN FABRICANTE F
ON P.CODIGO=D.CODIGO AND F.ID_FAB = D.ID_FAB
WHERE P.NOMBRE='FREDDY HARDEST';

SELECT P.*, R.MEDIO
FROM PROGRAMA P INNER JOIN REGISTRA R
ON P.CODIGO=R.CODIGO
WHERE R.MEDIO='INTERNET';

SELECT C.NOMBRE, R.MEDIO
FROM CLIENTE C INNER JOIN REGISTRA R
ON C.DNI = R.DNI
WHERE R.MEDIO='INTERNET';

SELECT P.*, R.MEDIO
FROM PROGRAMA P INNER JOIN REGISTRA R
ON P.CODIGO=R.CODIGO
WHERE R.MEDIO='TARJETA POSTAL';

SELECT C.CIUDAD, R.MEDIO
FROM COMERCIO C INNER JOIN REGISTRA R
ON C.CIF = R.CIF
WHERE R.MEDIO='INTERNET';

SELECT C.NOMBRE, R.MEDIO, P.NOMBRE, COM.NOMBRE
FROM CLIENTE C INNER JOIN REGISTRA R INNER JOIN PROGRAMA P INNER JOIN COMERCIO COM
ON C.DNI = R.DNI AND P.CODIGO=R.CODIGO AND COM.CIF=R.CIF;

SELECT F.NOMBRE, COM.NOMBRE
FROM FABRICANTE F INNER JOIN DESARROLLA DES INNER JOIN DISTRIBUYE D INNER JOIN PROGRAMA P INNER JOIN COMERCIO COM
ON F.ID_FAB = DES.ID_FAB AND P.CODIGO=DES.CODIGO AND P.CODIGO=D.CODIGO AND COM.CIF=D.CIF
WHERE F.NOMBRE='ORACLE';

SELECT C.NOMBRE AS USUARIOS, P.NOMBRE,P.VERSION
FROM CLIENTE C INNER JOIN REGISTRA R INNER JOIN PROGRAMA P
ON C.DNI = R.DNI AND P.CODIGO=R.CODIGO
WHERE P.NOMBRE='PARADOX' AND P.VERSION=2;

SELECT COUNT(DISTINCT NOMBRE)
FROM PROGRAMA;

SELECT COUNT(EDAD)
FROM CLIENTE
WHERE EDAD>40;

SELECT COUNT(CANTIDAD), C.CIF
FROM DISTRIBUYE D INNER JOIN COMERCIO C
ON C.CIF = D.CIF
WHERE C.CIF=1;

SELECT avg(CANTIDAD)
FROM DISTRIBUYE D INNER JOIN PROGRAMA P
ON D.CODIGO = P.CODIGO
WHERE P.CODIGO=7;

SELECT MAX(CANTIDAD)
FROM DISTRIBUYE D INNER JOIN PROGRAMA P
ON D.CODIGO = P.CODIGO
WHERE P.CODIGO=7;

SELECT COUNT(C.CIF)
FROM DISTRIBUYE D INNER JOIN PROGRAMA P
ON D.CODIGO = P.CODIGO
INNER JOIN COMERCIO C
ON C.CIF=D.CIF
WHERE P.CODIGO=7;

SELECT COUNT(C.DNI + COM.CIF), R.MEDIO
FROM CLIENTE C INNER JOIN REGISTRA R
ON C.DNI = R.DNI
INNER JOIN COMERCIO COM
ON COM.CIF=R.CIF
WHERE MEDIO='INTERNET';

