-- *************
-- BASES DE DATOS
-- EJERCICIO DE REPASO DDL Y DML
-- MODULO BBDD 25/26
-- LUCIA ELIZO GOMEZ
-- SQL EJEMPLOS CONSULTAS 1 TABLA
-- *************

CREATE DATABASE TEMA6;
USE TEMA6;

CREATE TABLE ALUMNO(
ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO1 VARCHAR(100) NOT NULL,
APELLIDO2 VARCHAR(100) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
ES_REPETIDOR ENUM('SI','NO'),
TELEFONO VARCHAR(9));

DESC ALUMNO;

INSERT INTO ALUMNO VALUES
(1, 'MARÍA', 'SÁNCHEZ', 'PÉREZ', '1990-12-01', 'NO', NULL), 
(2, 'JUAN', 'SÁEZ', 'VEGA', '1998-04-02', 'NO', 618253876), 
(3, 'PEPE', 'RAMÍREZ', 'GEA', '1988-01-03', 'NO', NULL), 
(4, 'LUCÍA', 'SÁNCHEZ', 'ORTEGA', '1993-06-13', 'SÍ', 678516294), 
(5, 'PACO', 'MARTÍNEZ', 'LÓPEZ', '1995-11-24', 'NO', 692735409), 
(6, 'IRENE', 'GUTIÉRREZ', 'SÁNCHEZ', '1991-03-28', 'SÍ', NULL), 
(7, 'CRISTINA', 'FERNÁNDEZ', 'RAMÍREZ', '1996-09-17', 'NO', 628349590), 
(8, 'ANTONIO', 'CARRETERO', 'ORTEGA', '1994-05-20', 'SÍ', 612345633), 
(9, 'MANUEL', 'DOMÍNGUEZ', 'HERNÁNDEZ', '1999-07-08', 'NO', NULL), 
(10, 'DANIEL', 'MORENO', 'RUIZ', '1998-02-03', 'NO', NULL); 

SELECT*FROM ALUMNO;

SELECT APELLIDO1,NOMBRE,'LITERAL'
FROM ALUMNO;

SELECT NOMBRE AS NOMBRE_ALUMNO  -- 'NOMBRE ALUMNO'  (si es separado)
FROM ALUMNO;

SELECT NOMBRE, FECHA_NACIMIENTO
FROM ALUMNO
WHERE APELLIDO1='SANCHEZ' AND APELLIDO2='PEREZ'
AND ES_REPETIDOR='NO';

SELECT*
FROM ALUMNO
WHERE FECHA_NACIMIENTO BETWEEN '1990-01-01' AND '1995-12-31'; -- NOT BETWEEN

SELECT*
FROM ALUMNO
WHERE NOMBRE LIKE 'A%'; -- NOT LIKE (empiezan por A) (terminan por '%A') ('L%A') ('LUC_A') ('_____')

SELECT*
FROM ALUMNO
ORDER BY ID DESC;

SELECT*
FROM ALUMNO
ORDER BY APELLIDO1 DESC,NOMBRE DESC 
LIMIT 2;

-- DESDE AQUI

CREATE TABLE CURSOS (
ID_CURSO INT PRIMARY KEY,
NOMBRE VARCHAR(20),
DURACION INT);

DESC CURSOS;

INSERT INTO CURSOS VALUES
(1,'CURSO 1',2),
(2,'CURSO 2',1),
(3,'CURSO 3',2),
(4,'CURSO 4',3);

SELECT*FROM CURSOS;
 
ALTER TABLE ALUMNO
ADD COLUMN ID_CURSO INT;

ALTER TABLE ALUMNO
ADD CONSTRAINT ALUMNO_CURSOS_FK 
	FOREIGN KEY (ID_CURSO)
    REFERENCES CURSOS(ID_CURSO)
    ON UPDATE CASCADE ON DELETE CASCADE;

DESC ALUMNO;

UPDATE ALUMNO
SET ID_CURSO=1
WHERE ID IN(1,2,3,4);

UPDATE ALUMNO
SET ID_CURSO=2
WHERE ID IN(5,6,7,8);

UPDATE ALUMNO
SET ID_CURSO=3
WHERE ID IN(9,10);

SELECT ID,ALUMNO.NOMBRE,CURSOS.NOMBRE
FROM ALUMNO,CURSOS
WHERE ALUMNO.ID_CURSO=CURSOS.ID_CURSO
AND ALUMNO.ID_CURSO=1;

SELECT ID,ALUMNO.NOMBRE,CURSOS.NOMBRE
FROM ALUMNO INNER JOIN CURSOS                    -- ES MEJOR USAR INNER JOIN
ON ALUMNO.ID_CURSO=CURSOS.ID_CURSO;

SELECT ID,ALUMNO.NOMBRE,CURSOS.NOMBRE
FROM ALUMNO INNER JOIN CURSOS
ON ALUMNO.ID_CURSO=CURSOS.ID_CURSO
WHERE ALUMNO.ID_CURSO=1;

SELECT ID,ALUMNO.NOMBRE,CURSOS.NOMBRE
FROM ALUMNO INNER JOIN CURSOS
USING (ID_CURSO);

CREATE TABLE AULAS (
ID_AULA INT PRIMARY KEY,
NOMBRE VARCHAR(20),
METROS_CUADRADOS INT);

ALTER TABLE CURSOS
ADD COLUMN ID_AULA INT;

ALTER TABLE CURSOS
ADD CONSTRAINT CURSOS_AULAS_FK
	FOREIGN KEY (ID_AULA)
    REFERENCES AULAS(ID_AULA)
    ON DELETE CASCADE ON UPDATE CASCADE;
    
INSERT INTO AULAS VALUES
(1,'AULA 1',8),
(2,'AULA 2',6),
(3,'AULA 3',3),
(4,'AULA 4',5);

UPDATE CURSOS
SET ID_AULA=1
WHERE ID_CURSO=1;

UPDATE CURSOS
SET ID_AULA=2
WHERE ID_CURSO=2;

UPDATE CURSOS
SET ID_AULA=3
WHERE ID_CURSO=3;

UPDATE CURSOS
SET ID_AULA=4
WHERE ID_CURSO=4;

SELECT ID,ALUMNO.NOMBRE,CURSOS.NOMBRE,AULAS.NOMBRE
FROM ALUMNO INNER JOIN CURSOS INNER JOIN AULAS
ON ALUMNO.ID_CURSO=CURSOS.ID_CURSO AND CURSOS.ID_AULA=AULAS.ID_AULA;

SELECT ID,ALUMNO.NOMBRE,CURSOS.NOMBRE,AULAS.NOMBRE
FROM ALUMNO 
	INNER JOIN CURSOS 
		ON ALUMNO.ID_CURSO=CURSOS.ID_CURSO 
	INNER JOIN AULAS
		ON CURSOS.ID_AULA=AULAS.ID_AULA
WHERE APELLIDO1='CARRETERO';

SELECT ID,ALUMNO.NOMBRE,CURSOS.NOMBRE,AULAS.NOMBRE
FROM ALUMNO 
	INNER JOIN CURSOS 
		ON ALUMNO.ID_CURSO=CURSOS.ID_CURSO 
	INNER JOIN AULAS
		ON CURSOS.ID_AULA=AULAS.ID_AULA
WHERE CURSOS.ID_CURSO IN(1,2);

INSERT INTO ALUMNO VALUES
(11, 'ANA', 'SÁNCHEZ', 'PÉREZ', '1990-12-01', 'NO', NULL, NULL);

SELECT ID,ALUMNO.NOMBRE,CURSOS.NOMBRE,AULAS.NOMBRE
FROM ALUMNO INNER JOIN CURSOS INNER JOIN AULAS
ON ALUMNO.ID_CURSO=CURSOS.ID_CURSO AND CURSOS.ID_AULA=AULAS.ID_AULA

INSERT INTO ALUMNO VALUES
(12, 'JUAN', 'MARTIN', 'PÉREZ', '1995-12-01', 'NO', NULL, NULL);

INSERT INTO CURSOS VALUES
(5,'CURSO 5',2,NULL),
(6,'CURSO 6',4,NULL);

SELECT C.ID_CURSO,C.NOMBRE,C.ID_AULA,A.ID_AULA,A.NOMBRE
FROM CURSOS C LEFT JOIN AULAS A
ON C.ID_AULA=A.ID_AULA;